### ISSUE TITLE
wrong UOM on Invoke-IcingaCheckUsedPartitionSpace with 1 TB Partitions

### ISSUE THREAD

**Issue by puseidr** [Icinga/icinga-powershell-plugins#113]
if you have a 1 TB Disk/Patition the cmdlet Invoke-IcingaCheckUsedPartitionSpace returns the wrong unit of measurement

```
Invoke-IcingaCheckUsedPartitionSpace -Verbosity 3 -Include E
[OK] Check package "Used Partition Space" (Match All)
\_ [OK] Partition E: 68.70167%
| 'partition_e'=68.70167%;;;0;100 'used_space_partition_e'=687.015381TB;;;0;999.998047
0
```
is should be 687.015381**GB** and not TB (the disk has a size of 1000,00 GB in the disk management tool)
![image](https://user-images.githubusercontent.com/2630551/100627933-f3aeea80-3327-11eb-9c8f-7dadab9d9d2a.png)

**Comment by LordHepipud** [comment]
Thank you for the feedback! This is a weird issue, because when I run it in my system, the data is correct:

```powershell
icinga> Invoke-IcingaCheckUsedPartitionSpace -Verbosity 2;

[OK] Check package "Used Partition Space" (Match All)
\_ [OK] Partition C: 53.04771%
\_ [OK] Partition G: 99.592863%
\_ [OK] Partition R: 53.77414%
| 'partition_c'=53.04771%;;;0;100 'partition_g'=99.592863%;;;0;100 'used_space_partition_r'=1.956668TB;;;0;3.638678 'used_space_partition_g'=1.811929TB;;;0;1.819336 'used_space_partition_c'=493.812012GB;;;0;930.882812 'partition_r'=53.77414%;;;0;100
```

Could it be that the problem is with drives having **exactly** 1 TB?
