### ISSUE TITLE
IcingaCheckUsedPartitionSpace show no details about Cluster-Shared Volumes

### ISSUE THREAD

**Issue by ErwinE** [Icinga/icinga-powershell-plugins#116]
Hello,

we changed our old windows checks to the icinga-powershell-plugins.
Before that we used the "check_disk.exe" where we had a detailed output about the partitions and the shared volumes:

```
'C:\Program Files\ICINGA2\/sbin/check_disk.exe' '-c' '5%' '-u' 'mb' '-w' '10%'
DISK OK - free space:C:\ 285033 MB (75%); C:\ClusterStorage\*****\ 559084 MB (13%); C:\ClusterStorage\*****\ 1239332 MB (30%); C:\ClusterStorage\*****\ 1120221 MB (27%); C:\ClusterStorage\*****\ 1059215 MB (25%); C:\ClusterStorage\*****\ 1524541 MB (36%); C:\ClusterStorage\*****\ 1382932 MB (53%); C:\ClusterStorage\*****\ 1514890 MB (36%); C:\ClusterStorage\*****\ 1672421 MB (40%); C:\ClusterStorage\*****\ 950 MB (96%); C:\ClusterStorage\*****\ 129752 MB (16%); C:\ClusterStorage\*****\ 2133116 MB (51%);
```

Now we changed this to Invoke-IcingaCheckUsedPartitionSpace, where we only get details about the C: partition

```
Invoke-IcingaCheckUsedPartitionSpace -Warning 90 -Critical 95 -Include @() -Exclude @() -Verbosity 3
[OK] Check package "Used Partition Space" (Match All)
\_ [OK] Partition C: 25.06986%
```

Is this a problem or a feature which hasn´t been implemented, yet?

Thank you very much!

**Comment by log1-c** [comment]
I would also like the check to able to monitor cluster shared volumes :)

**Comment by LordHepipud** [comment]
This is intended as for ClusterShared Volumes we are working on a different plugin collection, because we want to check them more deeply which just fits not into the regular partition check. Further details about this will be made public by the end of January at latest.

**Comment by LordHepipud** [comment]
I just wanted to follow up on this issue, as the new plugins have been released as preview. More can be read on the Icinga blog post: https://icinga.com/blog/2021/01/20/icinga-for-windows-hyper-v-and-cluster-plugins-preview/

I will resolve this issue now and look forward to feedback on the Cluster and Hyper-V plugins.

Thank you in advance!
