### ISSUE TITLE
PowerShell-Base-Object is missed

### ISSUE THREAD

**Issue by lbetz** [Icinga/icinga-powershell-plugins#118]
The base Object 'PowerShell base' is missed in the bundle file 'Plugins_Bundle.conf'.

**Comment by LordHepipud** [comment]
This is intended and the PowerShell base is shipped with an own config file.
The reason behind this is that Icinga does not allow to define multiple objects at the same time.  As you can export single commands with the Framework, you would always have to ensure the PowerShell base is already present.

In addition, in case the PowerShell case was present before and you would export everything, the PowerShell base would be available already and cause problems.

For that reason the entire plugin collection is shipping without the PowerShell base and as separate config file.

**Comment by lbetz** [comment]
Check
