### ISSUE TITLE
Invoke-IcingaCheckMemory doesn't accept % thresholds

### ISSUE THREAD

**Issue by log1-c** [Icinga/icinga-powershell-plugins#12]
Running the following command `'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' '-C' 'Use-Icinga; exit Invoke-IcingaCheckMemory' '-Critical' '90' '-Warning' '80'` yields the following result:
```
[UNKNOWN]: Icinga Invalid Input Error was thrown: ConversionUnitMissing
Unable to parse input value. You have to add an unit to your input value. Example: "10GB". Allowed units are: "B, KB, MB, GB, TB, PB, KiB, MiB, GiB, TiB, PiB".
```

If I try to run the command from the PowerShell directly, I can't see the outcome as the session closes immediately.
Running the command without thresholds works, but then there is not alarming (obviously)

I re-installed the  plugin scripts from the snapshot packages (installed via the PowerShell framwork) this morning and did an import it the Icinga Director.

Service definition:
![image](https://user-images.githubusercontent.com/24474580/74231575-2ddecb00-4cc7-11ea-8d79-f4bb03150820.png)

Am I overlooking something?

**Comment by log1-c** [comment]
Changed the thresholds to `80B` and `90B`:
```
Der Wert "90B" kann nicht in den Typ "System.UInt64" konvertiert werden. Fehler: "Die Eingabezeichenfolge hat das
falsche Format."

In C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\plugins\Invoke-IcingaCheckMemory.psm1:95 

Zeichen:10

+          $CriticalPercent = $Critical / $MemoryData['Memory Total Byt ...

+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException

    + FullyQualifiedErrorId : InvalidCastFromStringToInteger

 

Der Wert "80B" kann nicht in den Typ "System.UInt64" konvertiert werden. Fehler: "Die Eingabezeichenfolge hat das 

falsche Format."

In C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\plugins\Invoke-IcingaCheckMemory.psm1:103 

Zeichen:10

+          $WarningPercent = $Warning / $MemoryData['Memory Total Bytes ...

+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException

    + FullyQualifiedErrorId : InvalidCastFromStringToInteger

 

[CRITICAL] Check package "Memory Usage" - [CRITICAL] Used Bytes 
\_ [CRITICAL] Used Bytes: Value "2.16GB" is greater than threshold "0.00GB"

```

**Comment by Crited** [comment]
About the title _Invoke-IcingaCheckMemory doesn't accept % thresholds_ you need to use -WarningPercent or -CriticalPercent like 50 for 50% and it works for me.

That one is fixed with the latest commit: _Der Wert "90B" kann nicht in den Typ "System.UInt64" konvertiert werden. Fehler: "Die Eingabezeichenfolge hat das
falsche Format."_

Invoking the check with -Critical 90 without a unit returned that error code intentionally, but we could make Bytes default. Need further input on that @LordHepipud 

Pull Request #13 mentioned above will fix the above, _but_ not the question whether a Unit should be set by default. IMO: A unit should be set by the user.

**Comment by log1-c** [comment]
`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' '-C' 'Use-Icinga; exit Invoke-IcingaCheckMemory' '-CriticalPercent' '90' '-WarningPercent' '80'` doesn't work for me:
![image](https://user-images.githubusercontent.com/24474580/74248723-4f03e380-4ce8-11ea-801c-074a93708a98.png)
That was my initial starting point, why I updated the plugins.

**Comment by Crited** [comment]
My bad, I only tested it in the PowerShell directly.

_If I try to run the command from the PowerShell directly, I can't see the outcome as the session closes immediately._

Try: 
 PS> _powershell -C { use-icinga; Invoke-IcingaCheckMemory -CriticalPercent 90 -WarningPercent 80 }_

**Comment by log1-c** [comment]
``` 
PS C:\Windows\system32> powershell -C { use-icinga; Invoke-IcingaCheckMemory -CriticalPercent 90 -WarningPercent 80 }
[UNKNOWN]: Icinga Invalid Input Error was thrown: ConversionUnitMissing

Unable to parse input value. You have to add an unit to your input value. Example: "10GB". Allowed units are: "B, KB, MB, GB, TB, PB, KiB, MiB, GiB, TiB, PiB".
```

**Comment by LordHepipud** [comment]
This should be fixed already. Are you running the latest plugin snapshot?

**Comment by log1-c** [comment]
Nope, haven't updated since my last post, will try it now :)

**Comment by log1-c** [comment]
```
PS C:\Windows\system32> powershell -C { use-icinga; Invoke-IcingaCheckMemory -CriticalPercent 90 -WarningPercent 80 }
[OK] Check package "Memory Usage"
| 'memory_percent_used'=48.49%;80;90;0;100 'used_bytes'=1.94GB;3.2;3.6;0;4
0
```
works!
