### ISSUE TITLE
Invoke-IcingaCheckEventlog - ExcludeEventId not working II

### ISSUE THREAD

**Issue by i3astian** [Icinga/icinga-powershell-plugins#131]
Hello,

In the current version the problem mentioned in #19 is back again.
With commit [39d66e56fa8784e8c5c3d13e684ed4ee35ed13ae ](https://github.com/Icinga/icinga-powershell-plugins/commit/39d66e56fa8784e8c5c3d13e684ed4ee35ed13ae#diff-3c93af3e27fc1d205b7f31774f82b923ee4f6643616522f35723aa72ba721f60) the fix from commit [8dcf91e281817b60bf12be7461987d663a3a5d7b](https://github.com/Icinga/icinga-powershell-plugins/commit/8dcf91e281817b60bf12be7461987d663a3a5d7b) was reverted.

Maybe you can implement it in a way like this (Line 99-132):
```
            if ($skip) {
                continue;
            }

			if ($null -ne $IncludeEventId -Or $null -ne $IncludeMessage -Or $null -ne $IncludeSource) {    
				$skip = $TRUE;

				if ($IncludeMessage.Count -ne 0) {
					foreach ($inMessage in $IncludeMessage) {
						# Filter for specific message content
						if ([string]$event.Message -like [string]$inMessage) {
							$skip = $FALSE;
							break;
						}
					}
				}

				# We might be looking for specific event ids and 
				if ($IncludeEventId.Count -ne 0 -And $IncludeEventId -contains $event.EventId) {
					$skip = $FALSE;
				}

				# We might be looking for specific event sources
				if ($IncludeSource.Count -ne 0 -And $IncludeSource -contains $event.Source) {
					$skip = $FALSE;
				}

				if ($skip) {
					continue;
				}
			}

            $filteredEvents += $event;
        }
```

**Comment by LordHepipud** [comment]
Thank you for the input. Are you sure this is broken? In October I redesigned the plugin and so far all event Id's I want to monitor are returned. By using the `old fix` im sometimes not getting the results I want.

The new version matches for the `EventId` instead of the `InstanceId, which is the correct implementation.
