### ISSUE TITLE
Invoke-IcingaCheckMemory - please add commited memory

### ISSUE THREAD

**Issue by puseidr** [Icinga/icinga-powershell-plugins#14]
in the current version (1.0.0.-rc1 stable) the Invoke-IcingaCheckMemory cmdlet only looks at the physical memory. 
Could you please add the commited memory for the calculation (warning/crit) and performancedata. 

The commited memory is more importend for a windows administrator then the physical (wich is often not full, but the pagefile has a fixed size and is not auto-growing)

**Comment by LordHepipud** [comment]
We will add an additional check for monitoring the page file, to ensure we do not crowd one plugin with too many content and arguments for now.

This one is already on our roadmap including with some other topics.

Thank you for the info
