### ISSUE TITLE
Invoke-IcingaCheckDirectory - Exception Item not found

### ISSUE THREAD

**Issue by phil-or** [Icinga/icinga-powershell-plugins#142]
I recently configured CheckDirectory to see if a file exists or not. Great that we can use your check!!!

Check works, if the given path is available. But if the path is not found, the check is still [OK]. In my opinion it should be [UNKNOWN] otherwise you won't notice the problem:

![grafik](https://user-images.githubusercontent.com/36534023/109480151-7c4e3b80-7a7b-11eb-8072-9591c6248734.png)

Another improvement would also be to display the filename you are looking for in the plugin output. So you would see all information in the plugin output:

![grafik](https://user-images.githubusercontent.com/36534023/109480311-aa338000-7a7b-11eb-850d-56bbef7441f3.png)

**Comment by LordHepipud** [comment]
Hello, thank you for the issue. This is weird. I thought the path check was implemented with 1.3.0 already to return Unknown in case the target does not exist.
I will have a look on this.

Are you checking directly for a target file or a directory containing files?
First one could be done easily to add the result into the output. The last one might get a little too crowded especially with huge directories and filter matches.

**Comment by phil-or** [comment]
At the moment I use the check with arguments -path <directory-path> and -filenames <filename>
Maybe you could add the content of argument "-filenames" to the ouput?
Furthermore, what do you think about an optional argument "-extended-output" which show you all files found?

**Comment by LordHepipud** [comment]
This is fixed with v1.5.0
