### ISSUE TITLE
Invoke-IcingaCheckUpdates - improvements

### ISSUE THREAD

**Issue by jcharaoui** [Icinga/icinga-powershell-plugins#143]
Currently the `-Filter` option allows the plugin to limit considered updates to certain predefined criteria. However, it's not possible to do the reverse: only exclude matching updates, and consider all others.

In this instance, I would like to only exclude updates that match `Security Intelligence Update`, since those a published very frequently, and consider all other possible updates.

**Comment by LordHepipud** [comment]
Yeah this is a great idea and wanted to improve the filtering a lot already. Could we use this issue to collect some feedback on what everyone would be looking for on Windows updates?

The more input we get, the more we can improve on how results are handled and which updates are pending.

**Comment by jcharaoui** [comment]
An option to list the names of the updates in the result output.

**Comment by jcharaoui** [comment]
Options to filter or exclude certain update categories. For example, Windows Defender definition updates have a `Categories` property which contain `Definition Updates`. The plugin should be able to ignore those.

Another use-case for this is to consider only security-related updates.

**Comment by jcharaoui** [comment]
Also, I'm not sure if this issue is specific to the plugin, if it's by design, or if there's an off-by-one error somewhere:

When I specify the `-Warning 1` the plugin only warns if there are _more_ _than_ _one_ updates pending, instead of _one_ _or_ _more_. I work with a lot of Icinga2 plugins and it seems its the only one with this interpretation of a threshold.

**Comment by LordHepipud** [comment]
Thank you for all the input so far!

Regarding the thresholds, this is by design as we follow the Nagios/Icinga Plugin threshold guidelines: https://icinga.com/docs/icinga-for-windows/latest/plugins/doc/10-Icinga-Plugins/

Most of Icinga for Windows Plugins will follow these patterns and possibilities. The ones who don't are using direct matches for inputs or values not really compareable.

**Comment by jcharaoui** [comment]
> Regarding the thresholds, this is by design as we follow the Nagios/Icinga Plugin threshold guidelines: https://icinga.com/docs/icinga-for-windows/latest/plugins/doc/10-Icinga-Plugins/

Alright, thanks for the clarification on that point!
