### ISSUE TITLE
FeatureRequest: Plugin for file attributes

### ISSUE THREAD

**Issue by RincewindsHat** [Icinga/icinga-powershell-plugins#146]
It would be nice to have to have a pluging to check for certain file attributes, e.g. if the size is smaller/bigger than a threshhold.

**Comment by LordHepipud** [comment]
Hello, thank you for the input.

Does this plugin not fullfil your requirements: https://icinga.com/docs/icinga-for-windows/latest/plugins/doc/plugins/05-Invoke-IcingaCheckDirectory/

**Comment by RincewindsHat** [comment]
Hi, thanks for the answer. It actually does, but it didn't occur to me to look for that functionality under that name :-)

closed as far as I am concerned
