### ISSUE TITLE
Invoke-CheckNetworkInterface Exception calling "Add" with "2" argument(s)

### ISSUE THREAD

**Issue by ErwinE** [Icinga/icinga-powershell-plugins#148]
Hello,

we enabled the network interface check for over 600 windows systems.
On about 10% of our systems we get the same error. It´s seems that it´s especially on cluster systems.

**The command which is executed by all our Windows devices:**

_'Invoke-IcingaCheckNetworkInterface' '-IncludeNetworkDevice' '@()' '-ExcludeNetworkDevice' '@()' '-ExcludeInterfaceTeam' '@()' '-IncludeInterfaceTeam' '@()' '-Verbosity' '2'_

**The error from some systems:**
```
[UNKNOWN]: Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: '*****'  Key being added: '*****'"
CheckCommand: Invoke-IcingaCheckNetworkInterface

Arguments: -IncludeNetworkDevice System.Object[] -ExcludeNetworkDevice System.Object[] -ExcludeInterfaceTeam System.Object[] -IncludeInterfaceTeam System.Object[] -Verbosity 2
```

Has someone a idea where this error could come from?
If you need any further information just please ask.

Thank you very much!

Best Regards,
Erwin

**Comment by LordHepipud** [comment]
This is a very interesting issue. Does this relate to team interfaces or other interfaces as well?
For some reason it can happen that an interface with the same name is present, which causes issues.

**Comment by ErwinE** [comment]
I checked the systems and in our case this problem exist only for team interfaces.

**Comment by ErwinE** [comment]
> This is a very interesting issue. Does this relate to team interfaces or other interfaces as well?
> For some reason it can happen that an interface with the same name is present, which causes issues.

Hello @LordHepipud,
I checked the systems and in our case this problem exist only for team interfaces.
Thank you for your help!

**Comment by LordHepipud** [comment]
Could you please test if the linked PR resolved the issue and all data is displayed correctly for your team interfaces?

**Comment by ErwinE** [comment]
> Could you please test if the linked PR resolved the issue and all data is displayed correctly for your team interfaces?

Hi @LordHepipud,

I tested the new script on several systems and it seems that it´s now working without any problems.

Thank you very much!
