### ISSUE TITLE
Invoke-IcingaCheckUptime - Warning/Critical when uptime is lower than..

### ISSUE THREAD

**Issue by puseidr** [Icinga/icinga-powershell-plugins#15]
Could you please add a switch or parameter to the cmdlet to change the "problem-detection" method.

when the uptime is lower than x hours/days/whatever the cmdlet should return the warning/critical state instead of current behavior (uptime is higher then x).

**Comment by LordHepipud** [comment]
You can already do this, as all plugins comply with the Nagios/Icinga threshold guidelines.

http://nagios-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

You can simply specify this directly on the argument.

Note: If you are using a threshold config with a leading `@`, you will have to escape it:

```
`@
```
