### ISSUE TITLE
Invoke-IcingaCheckNetworkInterface - handling problem while defining thresholds as percentage values

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-plugins#150]
Hello,

I need to define any thresholds as percentage values:

`Invoke-IcingaCheckNetworkInterface -IncomingAvgBandUsageCrit 95% -OutboundAvgBandUsageCrit 95% -Verbosity 2`

This leads to:

`Invalid range specified for Critical argument: "95%"`

What is the right way to define this? 
An aditional example in the docs whould be nice.

**Comment by LordHepipud** [comment]
This is not yet possible because the data is fetched as Performance Counters which are a fixed number. To support this, we would manually require to calculate the % value for this value and pass it through.
