### ISSUE TITLE
Invoke-IcingaCheckEventlog - unable to process Hyper-V eventlogs

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-plugins#153]
Hello,

while configuring some Hyper-V eventlog checks it came to our attention that Invoke-IcingaCheckEventLog is unable to access these logs:

```
[UNKNOWN]: Icinga Invalid Input Error was thrown: EventLogLogName: Microsoft-Windows-Hyper-V-Worker-Admin
Failed to fetch EventLog information. Please specify a valid LogName.
```

Upon investigating this we found its a limitation of Get-EventLog, used in the eventlog provider [here](https://github.com/Icinga/icinga-powershell-plugins/blob/master/provider/eventlog/Get-IcingaEventLog.psm1#L79):

Scope of Get-EventLog:
![14-04-_2021_16-19-51](https://user-images.githubusercontent.com/34264690/114726036-4c15e000-9d3d-11eb-8051-52c0948f68a4.png)

Get-EventLog can only access eventlogs of the first tier. Unfortunately the majority of the Hyper-V eventlogs are located below:

![14-04-_2021_15-52-51](https://user-images.githubusercontent.com/34264690/114722928-82059500-9d3a-11eb-85c5-5ed330abfbfb.png)

According to Microsoft Get-EventLog is [**deprecated**](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-eventlog?view=powershell-5.1) (see 'Description'). Its successor [Get-WinEvent](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-7.1) was [introduced](https://www.computerperformance.co.uk/powershell/get-winevent/) with powershell 2.0. It was designed to replace the Get-EventLog cmdlet on computers running Windows Vista and later versions of Windows.

Get-WinEvent can access all eventlogs. Its also much faster:
![14-04-_2021_16-15-00](https://user-images.githubusercontent.com/34264690/114727113-39e87180-9d3e-11eb-8927-2988471adf09.png)

**Comment by LordHepipud** [comment]
The reason we stick with `Get-EventLog` by now, is that it allows proper filtering in advance, while `Get-WinEvent` requires afterwards filtering. This will require some testing in addition to allow the same amount of performance we can achieve right now.

**Comment by LordHepipud** [comment]
Could you please test the linked PR I added for this? This will replace `Get-EventLog` with `Get-WinEvent`

**Comment by K0nne** [comment]
I will test it.
