### ISSUE TITLE
installing plugins from PowerShell gallery automatically installs newest framework version

### ISSUE THREAD

**Issue by log1-c** [Icinga/icinga-powershell-plugins#162]
Hello :)

We are currently switching the installation of the Icinga agent, powershell framework and plugins from the older kickstart script to the installation via PowerShell gallery.
Today we stumble over something odd:
When installing the plugins in an older version the powershell framework automatically gets installed in its newest version.
Is this an intended behavior?

example from some manual testing with which we wanted to test updating already installed servers:
`$frameworkversion='1.1.2'`
`$pluginsversion='1.1.0'`

run at 1:21PM: `Install-Module -Name icinga-powershell-framework -RequiredVersion $frameworkversion -Force -Confirm:$false`
run at 1:22PM: ` Install-Module 'icinga-powershell-plugins' -RequiredVersion $pluginsversion -Force -Confirm:$false`

![image](https://user-images.githubusercontent.com/24474580/117653599-e3335380-b194-11eb-960d-e28075c6bfa0.png)
```powershell
Get-Module -Name icinga-powershell-framework

ModuleType Version    Name                                ExportedCommands                                                                                          
---------- -------    ----                                ----------------                                                                                          
Script     1.4.1      icinga-powershell-framework         {ConvertTo-IcingaSecureString, Disable-IcingaProgressPreference, Enable-IcingaUntrustedCertificateValid...

Get-Module -Name icinga-powershell-plugins

ModuleType Version    Name                                ExportedCommands                                                                                                                                                             
---------- -------    ----                                ----------------                                                                                                                                                             
Script     1.1.0      icinga-powershell-plugins           {Import-IcingaPlugins, Publish-IcingaPluginDocumentation, Use-IcingaPlugins}   
```

In case you need more input, please say so :)

best regards

**Comment by LordHepipud** [comment]
I honestly do not know on how PowerShell Gallery picks the dependencies of the modules.
For plugins v1.1.0 the dependency is set to Framework v1.1.0 - im not sure if it is preferred by PSGallery to install the latest version of a dependency instead.

In general it shouldn't cause any problems, as you can run a newer Framework version with older plugins, but not the other way around.

**Comment by log1-c** [comment]
closing this, as we haven't investigated this further, because we are staying with the installation via the packages/zip files.
