### ISSUE TITLE
Invoke-IcingaCheckService dows not work, when the service name has spaces

### ISSUE THREAD

**Issue by NeverUsedID** [Icinga/icinga-powershell-plugins#17]
I'am using the command configurations from the Icinga framework director basket.

If the servicename has spaces the check will not work. F.e. the "Sentinel RMS License Manager" service, where the displayname AND the servicename are the same. Thank you Sentinel for using that best practice....

`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' '-C' 'Use-Icinga; exit Invoke-IcingaCheckService' '-Service' 'Sentinel RMS License Manager' '-Status' 'Running'`

Will result in:

```
Invoke-IcingaCheckService : Cannot process argument transformation on
parameter 'Verbosity'. Cannot convert value "RMS" to type "System.Int32". 

Error: "Input string was not in a correct format."
At line:1 char:62
+ Use-Icinga; exit Invoke-IcingaCheckService -Service Sentinel RMS License 
Manager ...
+                                                              ~~~
+ CategoryInfo          : InvalidData: (:) [Invoke-IcingaCheckService], ParameterBindingArgumentTransformationException
+ FullyQualifiedErrorId : ParameterArgumentTransformationError,​Invoke-IcingaCheckService
```

This error can be provoked by testing any non existing service name with spaces, like
`
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe '-C' 'Use-Icinga; exit Invoke-IcingaCheckService' '-Service' 'my silly named service' '-Status' 'Running'
`

I think this could be solved by proper escaping, but i haven't found a way yet.

**Comment by LordHepipud** [comment]
Hello and thank you for the feedback. You will have to check with the service name instead of the display name for monitoring.

So it would be as example `icinga2` instead of `Icinga 2`.

**Comment by LordHepipud** [comment]
I just had a deeper loop on the error you are getting. Have you configured the `Verbose` argument somehow? Because this seems to be the main issue here.

**Comment by NeverUsedID** [comment]
HI,

the problem is, that these Sentinel Developers decided to use the same name for display AND Service name and throwing every standard over board, so the service name has " " in the name.

No, there is no Verbose mode set. I just execute the command mentioned in the post. No change at the code at all. It looks like that "RMS" is used as value for the next not setted parameter, which in this case is Verbosity

**Comment by NeverUsedID** [comment]
Solved by adding "'" around the service name like 'my service with spaces'

Still, a non existent service gives back "ok" in the master version on my last tests
