### ISSUE TITLE
Feature request: monitoring of MPIO properties

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-plugins#173]
Hello,

we whould love to monitor MPIO properties of systems with enabled HyperV feature:

Microsoft Multipath I/O (MPIO) is a Microsoft-provided framework that allows storage providers to develop multipath solutions that contain the hardware-specific information needed to optimize connectivity with their storage arrays.

`(gwmi -Namespace root\wmi -Class mpio_disk_info).driveinfo | select-object Name, NumberPaths,SerialNumber`

**Comment by K0nne** [comment]
Hello!

Thanks for the PR. I have tested it and I found an issue with the threshold logic.

The check aims to alert if some of the configured mpio paths are missing, so threshold values less than the current value need to be configured. I I do this the check behaves, as if the logic is inverted.

PS C:\WINDOWS\system32> icinga { **Invoke-IcingaCheckMPIO -Verbosity 2 -NumberPathWarn 7 -NumberPathCrit 6** }
```
[CRITICAL] Check package "Multipath-IO Package" (Match All) - [CRITICAL] MPIO Disk0 Number Paths, MPIO Disk1 Number Paths, MPIO Disk2 Number Paths, MPIO Disk3 Number Paths, MPIO Disk4 Number Paths
\_ [CRITICAL] Check package "ROOT\MPIO\0000_0 Package" (Match All)
   \_ [OK] ROOT\MPIO\0000_0 Active: True
   \_ [CRITICAL] Check package "ROOT\MPIO\0000_0 Drivers Package" (Match All)
      \_ [CRITICAL] MPIO Disk0 Number Paths: Value "8c" is greater than threshold "6c"
      \_ [CRITICAL] MPIO Disk1 Number Paths: Value "8c" is greater than threshold "6c"
      \_ [CRITICAL] MPIO Disk2 Number Paths: Value "8c" is greater than threshold "6c"
      \_ [CRITICAL] MPIO Disk3 Number Paths: Value "8c" is greater than threshold "6c"
      \_ [CRITICAL] MPIO Disk4 Number Paths: Value "8c" is greater than threshold "6c"
   \_ [OK] ROOT\MPIO\0000_0 NumberDrives: 5c
| 'mpio_disk0_number_paths'=8c;7;6 'mpio_disk3_number_paths'=8c;7;6 'mpio_disk4_number_paths'=8c;7;6 'mpio_disk2_number_paths'=8c;7;6 'mpio_disk1_number_paths'=8c;7;6 'rootmpio0000_0_numberdrives'=5c;;
2
```

PS C:\WINDOWS\system32> icinga { **Invoke-IcingaCheckMPIO -Verbosity 2 -NumberPathWarn 7** }
```
[WARNING] Check package "Multipath-IO Package" (Match All) - [WARNING] MPIO Disk0 Number Paths, MPIO Disk1 Number Paths, MPIO Disk2 Number Paths, MPIO Disk3 Number Paths, MPIO Disk4 Number Paths
\_ [WARNING] Check package "ROOT\MPIO\0000_0 Package" (Match All)
   \_ [OK] ROOT\MPIO\0000_0 Active: True
   \_ [WARNING] Check package "ROOT\MPIO\0000_0 Drivers Package" (Match All)
      \_ [WARNING] MPIO Disk0 Number Paths: Value "8c" is greater than threshold "7c"
      \_ [WARNING] MPIO Disk1 Number Paths: Value "8c" is greater than threshold "7c"
      \_ [WARNING] MPIO Disk2 Number Paths: Value "8c" is greater than threshold "7c"
      \_ [WARNING] MPIO Disk3 Number Paths: Value "8c" is greater than threshold "7c"
      \_ [WARNING] MPIO Disk4 Number Paths: Value "8c" is greater than threshold "7c"
   \_ [OK] ROOT\MPIO\0000_0 NumberDrives: 5c
| 'mpio_disk0_number_paths'=8c;7; 'mpio_disk3_number_paths'=8c;7; 'mpio_disk4_number_paths'=8c;7; 'mpio_disk2_number_paths'=8c;7; 'mpio_disk1_number_paths'=8c;7; 'rootmpio0000_0_numberdrives'=5c;;
1
```

**Comment by K0nne** [comment]
It turned out to be a handling problem. Correct usage is:

`Invoke-IcingaCheckMPIO -numberpathwarn 7: -numberpathcrit 6: -verbosity 2`

**Comment by Aleksey-Maksimov** [comment]
Hello
Undoubtedly, Invoke-IcingaCheckMPIO is a useful and necessary plugin.
But there is one problem. If we try to run it on a system without the MPIO components installed, the process simply crashes and closes. We need to check if MPIO is installed before attempting to access it.
