### ISSUE TITLE
Invoke-IcingaCheckTimeSync.psm1 doesn't detect time drift

### ISSUE THREAD

**Issue by davekempe** [Icinga/icinga-powershell-plugins#176]
Hi,
not sure if I'm doing it wrong or not, but the checkTimeSync plugin doesn't seem to work correctly. 
I don't know enough powershell to be able to suggest a fix, but as a feature request, maybe we could print out the local and remote time in verbose mode?

```
PS C:\Windows\system32>
>> Invoke-IcingaCheckTimeSync -Server '172.30.60.1' -TimeOffset 10ms -Warning 10ms -Critical 10ms -Verbosity 2
[OK] Check package "Time Package" (Match All)
\_ [OK] Sync Status: NoLeapWarning
\_ [OK] Time Offset: 0s
\_ [OK] Time Service: Running
| 'time_offset'=0s;0.01;0.01 'time_service'=4;;4
0
PS C:\Windows\system32> w32tm /stripchart /computer:172.30.60.1 /samples:4 /dataonly
Tracking 172.30.60.1 [172.30.60.1:123].
Collecting 4 samples.
The current time is 28/05/2021 6:39:15 AM.
06:39:15, -43149.7350583s
06:39:17, -43149.7349657s
06:39:19, -43149.7347674s
06:39:21, -43149.7346532s
PS C:\Windows\system32>
```

**Comment by LordHepipud** [comment]
Thank you for the issue. Just to get it right: Is the time actually offset with `-43149.7350583s`

What would be the current and expected time on the machine? We could add the local and remote time, but the Offset actually has to report it back properly.

**Comment by davekempe** [comment]
Its out by about 40 seconds. The machine (router) on 172.30.60.1 is in AEST(UTC +10) timezone, but that shouldn't matter for NTP. I noticed it as you can compare the seconds ticking away on these clocks and its definitely off.

**Comment by LordHepipud** [comment]
Could you please test the linked PR and check if the offset is now providing a negative value? In case it does, monitoring should be possible by providing the threshold value for the offset.
Every value below 0 should cause a warning/critical if you use the "simply" threshold configuration, like `-Warning 10s`

**Comment by davekempe** [comment]
Ah perfect that seems work correctly now!

```
>> Invoke-IcingaCheckTimeSync -Server '172.30.60.1' -TimeOffset 10ms -Warning 10ms -Critical 20ms -Verbosity 2
[CRITICAL] Check package "Time Package" (Match All) - [CRITICAL] Time Offset
\_ [OK] Sync Status: NoLeapWarning
\_ [CRITICAL] Time Offset: Value "-43192.26s" is lower than threshold "0s"
\_ [OK] Time Service: Running
| 'time_offset'=-43192.26s;0.01;0.02 'time_service'=4;;4
2
```

Thanks!

**Comment by LordHepipud** [comment]
You are welcome. Does it match the actual offset?
