### ISSUE TITLE
please remove human readable UOM from perfdata

### ISSUE THREAD

**Issue by puseidr** [Icinga/icinga-powershell-plugins#18]
In the current version (1.0.0) of  the Invoke-IcingaCheckMemory cmdlet the perfdata output is in "GB" instead of "B"(yte) like before. 

`[OK] Check package "Memory Usage"
| 'memory_percent_used'=46.96%;;;0;100 'used_bytes'=1.87GB;;;0;3.99`

This is a problem for Icinga2 installations with go-carbon/whisper/graphite. the GB value is not stored inside the whisper file so you don't have historical performance data in grafana :(

maybe this problem exists in other cmdlets, i just found it in the memory check

**Comment by LordHepipud** [comment]
Why are they not readable in Graphite/Grafana? In general these metrics should be covered by the tools and set the correct axis and displaying settings.

I will check this tomorrow on my test systems, as far as I can tell right now I didnt have a problem with the graphs.

**Comment by LordHepipud** [comment]
I just checked this issue and within my graphing (with some small gaps), the data is handled properly and stored.

![image](https://user-images.githubusercontent.com/5050288/75333777-0838f080-5887-11ea-9e5d-dc16feb7f4d2.png)

I digged down a little and the root-cause seems to be the Whisper Files of your graph for this specific services.
Could you please try to delete the Whisper file of the memory service for one host so it becomes re-created on the next check result?

This would be the fix, as in the previous version the UOM wasnt set but is now.

**Comment by m4k5ym** [comment]
Hellow,

I have to agree with @LordHepipud graph data are exposed as they are without UOM to Graphite.

Please look here:

```
(graphite) graphite-web@localhost:~$ whisper-dump.py /var/lib/graphite/whisper/icinga2/localhost_local/services/300/invoke-icingacheckmemory/memory/perfdata/used_bytes/value.wsp | head -n 120
...
Archive 0 data:
0: 1587736200, 2480343613.440000057220458984375
1: 1587736500, 2480343613.440000057220458984375
2: 1587736800, 2480343613.440000057220458984375
3: 0,          0
4: 1587737400, 2480343613.440000057220458984375
5: 1587737700, 2480343613.440000057220458984375
6: 1587738000, 2480343613.440000057220458984375
7: 1587738300, 2512555868.159999847412109375
8: 1587738600, 2501818449.9200000762939453125
9: 1587738900, 2501818449.9200000762939453125
10: 1587739200, 2501818449.9200000762939453125
11: 1587739500, 2501818449.9200000762939453125
12: 1587739800, 2512555868.159999847412109375
13: 1587740100, 2512555868.159999847412109375
14: 1587740400, 2523293286.400000095367431640625
15: 1587740700, 2523293286.400000095367431640625
16: 1587741000, 2534030704.639999866485595703125
17: 1587741300, 2534030704.639999866485595703125
18: 1587741600, 2544768122.88000011444091796875
19: 1587741900, 2534030704.639999866485595703125
20: 1587742200, 2566242959.360000133514404296875
21: 1587742500, 1363652116.480000019073486328125
22: 1587742800, 1374389534.7200000286102294921875
23: 1587743100, 1879048192
24: 1587743400, 1846835937.2799999713897705078125
25: 1587743700, 2244120412.159999847412109375
26: 1587744000, 2684354560
27: 1587744300, 2587717795.840000152587890625
28: 1587744600, 2576980377.599999904632568359375
29: 1587744900, 2523293286.400000095367431640625
30: 1587745200, 2544768122.88000011444091796875
31: 1587745500, 2609192632.320000171661376953125
32: 1587745800, 2598455214.0799999237060546875
33: 1587746100, 2652142305.280000209808349609375
34: 1587746400, 2727304232.96000003814697265625
35: 1587746700, 2738041651.19999980926513671875
36: 1587747000, 2748779069.440000057220458984375
37: 1587747300, 2748779069.440000057220458984375
38: 1587747600, 2780991324.159999847412109375
39: 1587747900, 2759516487.679999828338623046875
40: 1587748200, 2673617141.7600002288818359375
```

First of all consult your Icinga 2 log file because if Icinga 2 would expose invalid perfdata they would fail at first here with a message like "`warning/GraphiteWriter: Ignoring invalid perfdata for checkable`". Then you should check you go-carbon log file maybe your disk is full or something else is happening.

Then you should verify with `whisper-info.py` and `whisper-dump.py` if your whisper archive is properly set up regarding your storage-schema configuration.

Last but not least here is an another living example:
![icinga-powershell-memory](https://user-images.githubusercontent.com/38684218/80239304-46bd1280-8660-11ea-9890-1bd8d4ad639e.png)

Greetings

**Comment by LordHepipud** [comment]
As this is in my opinion not a plugin issue, I will close it.
