### ISSUE TITLE
Invoke-IcingaCheckUpdates only returns OK as status code

### ISSUE THREAD

**Issue by MikeKall** [Icinga/icinga-powershell-plugins#184]
Hello!

I am using the `Invoke-IcingaCheckUpdates` and I have noticed that the exit code of the command is every time 0 (no matter if there are pending updates), so icinga shows the service as always ok. 

![image](https://user-images.githubusercontent.com/25392160/120301061-cb9b4680-c2cc-11eb-9ce2-7617f76fd0e0.png)
 
As you can see in the image the output of the script is WARNING and the Service status is OK. 
Is this how it suppose to work?

Thanks,
Mike

**Comment by LordHepipud** [comment]
Hello

Thank you for the issue. How is your CheckCommand defined? The plugins ship with pre-compiled CheckComands for Icinga 2 natively (.conf files) and Icinga Director Baskets (.json files).

The problem in your example is, that at the very bottom you see **1**

This is the actual state of the plugin. Calling a plugin will output the plugin message, as in your case the warning context, and **1**, which defines the `exit code`

In your check command configuration, your are not exiting the PowerShell properly, which should for example be

```
exit Invoke-IcingaCheckUpdates <your arguments>;
```

or in case you are calling a PowerShell from a PowerShell:

```
powershell -C { exit Invoke-IcingaCheckUpdates <your arguments>; }; exit $LASTEXITCODE;
```

**Comment by MikeKall** [comment]
Ah thank you very much!

**Comment by LordHepipud** [comment]
You are welcome :)
