### ISSUE TITLE
Invoke-IcingaCheckDirectory - PermissionDenied 

### ISSUE THREAD

**Issue by phil-or** [Icinga/icinga-powershell-plugins#196]
Another Exception handling bug, similar to #142 

Check should be UNKNOWN if there is a permission error:
![grafik](https://user-images.githubusercontent.com/36534023/120995125-668c9880-c785-11eb-99fb-7faf94c6714f.png)

Another improvement would be to display the filename and threshold you are looking for in the plugin output. So you would see all information in the plugin output and its easier for Icinga users for troubleshooting
![grafik](https://user-images.githubusercontent.com/36534023/120996402-92f4e480-c786-11eb-8cb0-d337616b8724.png)

**Comment by LordHepipud** [comment]
Thank you for the issue. The previous fix did not count in possible permission errors, thats something we can resolve.

For the plugin output it is more complicated in my oppinion. If you have a huge amount of files within a directory (example backups and backup files) you can easily generate a lot of plugin output.

We had customers with >1000 files processed by the plugin. If all of them would be displayed and added, it would be a little too much. But I'm sure we can improve something there.

**Comment by phil-or** [comment]
I agree with you that it's too much if you show all counted files in the plugin output, but thats not what I mean.

For example:
![grafik](https://user-images.githubusercontent.com/36534023/121324070-acc23300-c910-11eb-982a-7507b02c3cb1.png)

Without a look at the variables, one does not recognize at first sight where the problem is. So you have to check the custom variables. Assume there are users who are not so familar with icingaweb, they can't interpret the output.

So it would be beneficial to see the files (icingacheckdirectory_array_filenames) and filesize you are looking for in the plugin output.

**Comment by LordHepipud** [comment]
I see. I will try to work something out and create a PR for testing
