### ISSUE TITLE
service performace

### ISSUE THREAD

**Issue by haytxy** [Icinga/icinga-powershell-plugins#205]
hello,

Could you advise is it possible to monitor a windows service with CPU utilization perf-data and the possibility to set a threshold for it. For example, if CPU utilization for exact service will be on zero or near-zero then the critical status will occur?

https://icinga.com/docs/icinga-for-windows/latest/plugins/doc/10-Icinga-Plugins/

**Comment by LordHepipud** [comment]
Hello,

thank you for the issue. This is not yet possible, but we are working on something like this to monitor CPU and Memory usage directly for specific services.

This will either be included with 1.6.0 or 1.7.0, depending on other features and plugins.

**Comment by LordHepipud** [comment]
It will work similar to the current CPU and memory usage.

Each single process listed on the service will own the CPU usage and memory consumption. You can use filters to only include `msedge` for example and in addition or global set the CPU threshold of 70% and 1GB of memory.

The thresholds will work like any other plugins and will allow the Icinga threshold syntax for this. So basically you can check if a service is sitting on 0% CPU load or any other value, including ranges.

**Comment by LordHepipud** [comment]
I just added a new plugin on the linked PR, providing the requested features.
Maybe you can test it if you have the time.
