### ISSUE TITLE
Invoke-IcingaCheckEventlog..  Invalid JSON primitive 

### ISSUE THREAD

**Issue by drapiti** [Icinga/icinga-powershell-plugins#206]
The following eventlog check seems to have some bug.  [UNKNOWN] Icinga Exception: Invalid JSON primitive: .
This eventlog at the moment has 4 event id's which are aimed at tracking a windows reboot. Occasionally we are seeing the following error after testing a reboot. We tested starting a downtime, rebooting the server exiting the downtime and then we are seeing the check in the below state.  Threshold of events set to 0.

![image](https://user-images.githubusercontent.com/4235359/125094683-c0a9b200-e0d3-11eb-9d96-64a3bba03b59.png)

threshold Critical: 0
array of eventId's: 41, 1074, 6006, 6008
logname: System

Any ideas?

**Comment by drapiti** [comment]
Different server:
![image](https://user-images.githubusercontent.com/4235359/125100235-26e50380-e0d9-11eb-9416-cd648e6037a6.png)

**Comment by LordHepipud** [comment]
To me it seems like that for some reason the cache file got corrupted and therefor cannot be read anymore. Does this error vanish over time or does this error proceed?

Could you please share, which files are present inside `\cache\provider\eventlog\` as well as the content for each file present, including the file name?

**Comment by drapiti** [comment]
![image](https://user-images.githubusercontent.com/4235359/125107908-a1b21c80-e0e1-11eb-9894-4b96b3925870.png)

First file Contents:
{
    "12113514810213931351301422512451320228210131249114183.lastcheck":  132703192817037641
}
{
    "12113514810213931351301422512451320228210131249114183.lastcheck":  132703192817037641
}

Second File Contents:
{
    "21140125218116671371561712921616815715511393946668138.lastcheck":  132703191446946979
}

Third file contents:
{
    "22221011412136818816124321312925184142255138732006497.lastcheck":  132703178569924556
}

**Comment by drapiti** [comment]
Just seen it once or twice at the moment. Will test over the next few days.

**Comment by LordHepipud** [comment]
Is the first entry a copy&paste error or are there really two times the same content inside, without being separated by `,`?

**Comment by drapiti** [comment]
> Is the first entry a copy&paste error or are there really two times the same content inside, without being separated by `,`? Because then this should be the issue. Just wondering on how two times the same key and content can be added to the same file.

No error exactly the contents of the file.

**Comment by LordHepipud** [comment]
This would be fixed with Icinga for Windows v1.6.0: https://github.com/Icinga/icinga-powershell-framework/pull/351
