### ISSUE TITLE
[Feature-Request] Invoke-IcingaCheckService Filter Service Startup type not only Service status

### ISSUE THREAD

**Issue by ferencmatyas** [Icinga/icinga-powershell-plugins#211]
Hello,

I have many services with random names at the end so I use wildcard *. I would like to check Status Running but only if Service has Startup type Automatic. Now the Manual startup type is also matched and throwing an error. Can this be implemented? Maybe also with Startup type Automatic (Delayed Start) as some services use it. 

PS C:\Windows\system32> Invoke-IcingaCheckService -Service ABCD* -Exclude $null -Status Running -Verbosity 3
[CRITICAL] Services: 1 Critical 2 Ok [CRITICAL] Service "ABCD_manual" (Stopped) (All must be [OK])
\_ [OK] Service "ABCD_automatic": Running
\_ [CRITICAL] Service "ABCD_manual": Stopped is not matching threshold Running
\_ [OK] Service "ABCD_automatic": Running

Thank you,
Regards
Ferenc

**Comment by LordHepipud** [comment]
Hello and thank you for the issue.

If you leave `-Service` empty, the plugin will by default check all services which are configured as `Automatic` and not report Critical in case the service is not running, if the exit code of the service is not 0.

If a service is set to startup `Automatic` and gracefully shut down, the exit code is 0 and therefor will not report critical.

Does this help?

**Comment by ferencmatyas** [comment]
Hello, thanks for the reply. 
Unfortunately I cannot put the not running service on Automatic, it has to be on Manual. Also with Automatic a maintenance reboot triggers the service to start, what is not needed. The check belongs to a service set what only checks this ABCD* service. Can I add a -StartupType switch to the downloaded installation somehow?
Thank you!

**Comment by LordHepipud** [comment]
Right now this is not supported by the plugin, as it was not needed to make differentiation for this.

We could add this for 1.6.0 to allow filtering of services and the startup type.

**Comment by ferencmatyas** [comment]
Hello, thanks for the reply. It would be great to have it in the next version, thanks a lot for your support!
