### ISSUE TITLE
Invoke-IcingaCheckUsedPartitionSpace - partitions on dynamic disks are false / not queried

### ISSUE THREAD

**Issue by wrkhunte** [Icinga/icinga-powershell-plugins#213]
We use dynamic disks with multiple partitions. If it is necessary, partitions are expanded, which means that partitions are also displayed multiple times in diskmgmt.msc, although they are only there once. Here´s an example:
![image](https://user-images.githubusercontent.com/84439716/126438075-298e6492-f152-417d-b1ae-2ebf418f7fae.png)

With the Powershell plugins 1.5.0 this led to the following error:
```
Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: '1'  Key being added: '1'"
At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\provider\disks\Get-IcingaDiskPartitionAssignment.psm1:53 char:13
+             $PartitionInformation[$DiskId].Partitions.Add(
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

```

The current commit (1.6.0) of #189  avoids this error, but it turns out that "Invoke-IcingaCheckUsedPartitionSpace" only queries the "hard disk" itself and not the individual partitions on the disk.
Instead of small partitions (A: \, B: \, D: \, E: \) the check only takes the whole disk and gives it the drive letter of the 1st partition (A: \)
it looks like this: (C: \ and L: \ are on other hard drives)
```
[CRITICAL] Used Partition Space: 1 Critical 2 Ok [CRITICAL] Partition A: (99.12% (64.91TiB)) (All must be [OK])
\_ [CRITICAL] Partition A: 99.12% (64.91TiB) is greater than threshold 95% (62.22TiB)
\_ [OK] Partition C: 20.56% (91.57GiB)
\_ [OK] Partition L: 23.65% (881.15GiB)
| 'partition_c'=98327690000B;430517700000;454435350000;0;478353000000 'partition_a'=71374350000000B;64808253000000;68408711500000;0;72009170000000 'partition_l'=
946128700000B;3600585900000;3800618450000;0;4000651000000 
```
It is not currently possible for me to query the partitions B: \ D: \ ... and the values of A: \ are completely wrong because it takes the size of the entire hard disk instead of that of the partition itself.

**Comment by LordHepipud** [comment]
Thank you for the issue. The partition plugin at the moment, is designed to fetch all physical disks and related information for these disks.

For example, if you are having Disk 0 with three partitions, each data for each partition is listed on the plugin output.
This includes the current size of the partition and the maximum size.

I will have to setup a test environment with a dynamic disk including multiple and identical partitions to test this.

**Comment by wrkhunte** [comment]
Hello @LordHepipud,
with the new version of the plugin it works if I set the parameter "CheckUsedSpace".

Example:

> "Invoke-IcingaCheckPartitionSpace -Warning 90% -Critical 95% -CheckUsedSpace"
> 
> [WARNING] Used Partition Space: 1 Warning 12 Ok [WARNING] Partition D: (DATA) (93.07% (186.08GiB))
> \ _ [WARNING] Partition D: (DATA): 93.07% (186.08GiB) is greater than threshold 90% (179.94GiB)

If I leave out the "CheckUsedSpace" parameter and adjust the values accordingly, I get the error message that the "Warning value" is greater than the "Critical value".

Example:

> Invoke-IcingaCheckPartitionSpace -Warning 10% -Critical 5%
> 
> [UNKNOWN] Free Partition Space: 13 Unknown [UNKNOWN]
> ...
> \ _ [UNKNOWN] Partition D: (DATA): Warning threshold range "10% (19.99GiB)" is greater than Critical threshold range "5% (10.00GiB)"

Have I missed an adjustment?

**Comment by LordHepipud** [comment]
I think that is still a bug in the plugin itself. I will have a look and report back when I fixed it. I assume I forgot to change on how the values are compared to the thresholds. My bad!

**Comment by LordHepipud** [comment]
Ah, figured it out. You need to use the plugin threshold logic to reverse the output. By default, the thresholds are interpreted from range `< 0 or > 20`. But you will have to modify them, to represent the proper values:

https://icinga.com/docs/icinga-for-windows/latest/plugins/doc/10-Icinga-Plugins/

**Comment by wrkhunte** [comment]
Perfect, I have now changed the values from "5%" and "10%" to "5%:" and "10%:", that worked.
