### ISSUE TITLE
[feature-request] Invoke-IcingaCheckUsedPartitionSpace - possibility to check for free space

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga-powershell-plugins#214]
The "old" check command `disk-windows` (`check_disk.exe`) offers the param `disk_win_show_used` to change the check behavior between used or free space. We for example are checking the disk C: for free space (to be sure to have enough free space for auto deployment, auto update etc.) and every other disk the used space. 

It would be great to have this opportunity also with the icinga-powershell-plugins. So we can also replace the old check with the new modern PS check.

**Comment by LordHepipud** [comment]
Yes we were already considering this by renaming the current check from `Invoke-IcingaCheckUsedPartitionSpace` to `Invoke-IcingaCheckPartitionSpace` which offers a switch to change the default behavior from `used` to `free`.

For compatibility, there will be an alias available to not destroy current implementations.

**Comment by stevie-sy** [comment]
Oh great news! Thank you!
