### ISSUE TITLE
Invoke-IcingaCheckTimeSync Warning or Criticials only with positive value working

### ISSUE THREAD

**Issue by CHOOH1992** [Icinga/icinga-powershell-plugins#240]
Hi,
I noticed that _Invoke-IcingaCheckTimeSync_ will allways go _warning_ the result is negative.

![image](https://user-images.githubusercontent.com/84079532/140121823-d6069a6f-2fd7-4d37-b876-13ad1e789263.png)

Could you check this?

Best regards

**Comment by LordHepipud** [comment]
Thank you for the issue. According to the [plugin threshold guidelines](https://icinga.com/docs/icinga-for-windows/latest/plugins/doc/10-Icinga-Plugins/) this is the correct behavior. By using 500ms, your `Ok` range is from 0 to 500ms.

If you want negative values entirely, you can use `~:500ms`. If you want to include a negative value as well, you can use `-200ms:500ms` as example.

**Comment by CHOOH1992** [comment]
Nice! Never read this article, actually. Thanks for the assistance.
Best Regards
