### ISSUE TITLE
Invoke-IcingaCheckUsedPartitionSpace - Missing percentage perf data

### ISSUE THREAD

**Issue by StythEU** [Icinga/icinga-powershell-plugins#248]
Hey,

unfortunately, I had to realize that the check no longer provides perf data in percent. Is this a bug or is it intentional? 
Currently the version 1.6 is used, but in my Test-VM, where I use the 1.7, this data is also missing.

**Comment by LordHepipud** [comment]
Thank you for the issue. Yes, this is correct - the percentage output is no longer available in the output.
The reason for that is, that we provide all data to calculate the % value within solutions like Grafana for displaying them there.

As you can still use % as threshold argument, we did not see the reason to add additional perf data.

**Comment by StythEU** [comment]
Okay, thanks for your quick reply. It's a pity that these are no longer included, because now I have to rebuild my Grafana and, among other things, can no longer work with wildcards, at least this isn't known to me.

**Comment by StythEU** [comment]
Okay, I found a way to calculate it by wildcard. That settles the question.
