### ISSUE TITLE
Invoke-IcingaCheckUsedPartitionSpace - Icinga Invalid Configuration Error was thrown

### ISSUE THREAD

**Issue by CHOOH1992** [Icinga/icinga-powershell-plugins#250]
Hey,
i installed the plugins version 1.7.0 to several of our Windows Server Systems. On two Windows Server 2012 R2 I am actually unable to execute the _Invoke-IcingaCheckUsedPartitionSpace_-Command.

**Icingaweb2 output:**
```
Plugin Output
[UNKNOWN]: Icinga Invalid Configuration Error was thrown: PluginNotInstalled: Invoke-IcingaCheckUsedPartitionSpace
The plugin assigned to this service check seems not to be installed on this machine. Please review your service check configuration for spelling errors and check if the plugin is installed and executable on this machine by PowerShell. You can ensure modules are available by manually importing them by their name with the following commands: Import-Module -Name "module name" -Force; Import-Module -Name "module name" -Global -Force;
```

This:
```
Import-Module icinga-powershell-plugins -force;
Import-Module icinga-powershell-plugins  -global -force;
```
Didnt change anything actually.. 

You got any idea on how to fix this? Reinstallling the plugin did not work.
Best regards

**Comment by LordHepipud** [comment]
Does it work on the other machines just fine? Are only those two 2012 R2 machines affected?
Do other 2012 R2 machines work?

With v1.7.0 we renamed the plugin to `Invoke-IcingaCheckPartitionSpace`, but added an alias for `Invoke-IcingaCheckUsedPartitionSpace`.

Does the local execution of the plugin inside a PowerShell work on these machines?

**Comment by CHOOH1992** [comment]
Hi,
thanks for the fast reply. In Powershell 4.0 the alias is not working; the new check _Invoke-IcingaCheckPartitionSpace_ is present and working. In Powershell 5 on Server 2012 R2 everything is fine. Please feel free to close this issue.
Except that CheckUsedSpace now checks the free space; but that is actually easier to handle.
Thanks for your help

**Comment by LordHepipud** [comment]
Thank you for the input! Didn't think about that. For the monitoring: There is a new argument `-CheckUsedSpace`.
With this you can toggle back to the previous behavior and do both, free and used space monitoring.

I will work something out regarding the alias not working on those old machines.

**Comment by CHOOH1992** [comment]
Thanks for the reply. Actually this parameter is making stuff worse in my opinion, as the older version will not be able to process that one.

This results in an UNKOWN state.

Best regards

**Comment by ErwinE** [comment]
Hello!

We updated all our Icinga Clients to the newest Powershell Framework & Plugins and we have the same problem on all our 2012 R2 Windows Servers. The problem only occurs with the IcingaCheckUsedPartitionSpace check, all other checks are working fine.

[UNKNOWN]: Icinga Invalid Configuration Error was thrown: PluginNotInstalled: Invoke-IcingaCheckUsedPartitionSpace
The plugin assigned to this service check seems not to be installed on this machine. Please review your service check configuration for spelling errors and check if the plugin is installed and executable on this machine by PowerShell. You can ensure modules are available by manually importing them by their name with the following commands: Import-Module -Name "module name" -Force; Import-Module -Name "module name" -Global -Force;

**Comment by CHOOH1992** [comment]
Hi,
please try _Invoke-IcingaCheckPartitionSpace_ instead of _Invoke-IcingaCheckUsedPartitionSpace_. But keep in mind that this will check the free space (!). If you want the used space you can use this (new) argument: 
-CheckUsedSpace

Best regards

**Comment by LordHepipud** [comment]
Sorry for the late response. Can you please try the linked PR?
This should resolve the problem.

**Comment by ErwinE** [comment]
> Sorry for the late response. Can you please try the linked PR? This should resolve the problem.

Thanks for implementing the fix!
I tried it on two of our 2012 Systems and it works now without any problems.
