### ISSUE TITLE
Invoke-IcingaCheckCPU - The docs maybe wrong for param "ThresholdInterval"

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga-powershell-plugins#260]
The docs describe the param "ThresholdInterval". In the source code of the check I don't find it. Does it still exists? If yes, the link https://icinga.com/docs/icinga-for-windows/latest/doc/service/10-Register-Service-Checks/ in the description doesn't work (HTTP Code 404)

**Comment by LordHepipud** [comment]
Hello,

yes it does exist. This is a argument which is added and evaluated during runtime and is not present for the plugin itself, as we wanted a generic approach for this without requiring developers to take care of that.

The code for this is within the Framework for the `New-IcingaCheck` function.

**Comment by stevie-sy** [comment]
Ok thanks for explanation. So than is the mentioned link in the docs is wrong (in the the description field of the param). If you want to follow it you get the 404 code ;-)
That explains my confusion

**Comment by LordHepipud** [comment]
Yeah thats true. We made many changes on the docs and it seems some dead links survived. The documentation will be updated with v1.8.0 even more and then we can hopefully resolve the missing broken links.

**Comment by LordHepipud** [comment]
Fixed with v1.8.0
