### ISSUE TITLE
Invoke-IcingaCheckUsedPartitionSpace wrong result

### ISSUE THREAD

**Issue by patx90** [Icinga/icinga-powershell-plugins#273]
The check returns Warning or Error for some drives:
![grafik](https://user-images.githubusercontent.com/63921416/152223765-fe289555-344a-43ff-aadb-cc63aa6a14c8.png)

The drive is nealy empty:
![grafik](https://user-images.githubusercontent.com/63921416/152223822-740c6747-c259-48c6-ae36-9325176fb2ea.png)

**Comment by LordHepipud** [comment]
Thank you for the issue.
Which version of the plugins are you running?

The behavior seems fine to me, as you are comparing the free space with the thresholds a `>=`

In order for your call to return the correct result, it should look like this:

```powershell
Invoke-IcingaCheckUsedPartitionSpace -Warning '85%:' -Critical '95%:' -Verbosity 3
```

This will properly the free state, but in this case you might run into: https://github.com/Icinga/icinga-powershell-framework/issues/435

**Comment by LordHepipud** [comment]
As alternative, you can check the used space of the partitions:

```powershell
Invoke-IcingaCheckUsedPartitionSpace -Warning '85%' -Critical '95%' -Verbosity 3 -CheckUsedSpace
```

By default the plugin will use free space since the latest version.

**Comment by LordHepipud** [comment]
I just re-tested this as I weren't sure entirely: Both of the two options metioned above will work without problems, as long as the compare unit is identical.

**Comment by nbiada** [comment]
If this command use the old 32bit WMI approach every partition over 2Tb is in error

**Comment by LordHepipud** [comment]
I don't think this is the problem, as I'm using the plugins to check for 12TB partition without problem.
Depending on the version of the plugin `Invoke-IcingaCheckUsedPartitionSpace` will default to the free space and requires the `-CheckUsedSpace` argument.

This plugin is just an alias for `Invoke-IcingaCheckPartitionSpace` in newer versions.

**Comment by patx90** [comment]
Thank you for the clarification.
Using the parameter "-CheckUsedSpace" fixed my issue.
