### ISSUE TITLE
Feature/Enhancement: Invoke-IcingaCheckUpdates / Check for pending reboot 

### ISSUE THREAD

**Issue by Temportant** [Icinga/icinga-powershell-plugins#276]
After installing windows updates, sometimes a reboot is required. It would be nice, if Invoke-IcingaCheckUpdates could also check this registrykey for a pending reboot. 
HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired
Without the reboot the systems are not fully patched and sometime strange problems occur.

**Comment by LordHepipud** [comment]
Thanks for the input. This is definately something we are going to add with the next release!

**Comment by Skeletitor** [comment]
Hi,
this works. 

Just sharing my thoughts. Wouldnt ist be better to have a own check for pending reboots? Pending reboots can have more causes than a simple Windows Update ... so there are more than one RegKeys to check -> https://github.com/adbertram/Random-PowerShell-Work/blob/master/Random%20Stuff/Test-PendingReboot.ps1
