### ISSUE TITLE
Invoke-IcingaCheckScheduledTask ignore certain return codes

### ISSUE THREAD

**Issue by Paul-Weisser** [Icinga/icinga-powershell-plugins#282]
I started monitoring different Windows-Tasks with the Invoke-IcingaCheckScheduledTask commandlet.

One of these tasks is running pretty long (about 45 Minutes). While this task is running the check-command returns a non 0 return code 41301 (task is running). If I do not ignore the return codes it will show up as critical, which is not specifically the "correct" result in this case. So I have to ignore the return codes for now.

I see two possible ways around this problem. One would be to ignore this specific exit code if the state "Running" is allowed. The other one is to add another configuration-parameter to give a list of return codes that should specifically be ignored, e.g. 41301 for task is running or  41306 for task has been terminated by the user. Maybe even implement both solutions?

Opinions on this?

**Comment by LordHepipud** [comment]
Interesting - thank you for the report. I just had a look on a machine on which I configured a never ending task.
As far as I can tell, the exit code is set in case a task interrupted during runtime (reboot for example) and not completed properly.

Which means 41301 describes the task would actually never end and interrupted before. You can even test this by running a PowerShell command within an endless loop.

The best option would be to add a exclude list for exit codes users do not want to include in the result. On the other hand, this will make it even harder to catch an error if a user really terminated a task which should run.

Regardless of the solution, there is in my opinion always a catch. Even when we add a flag to ignore the exit status, you will never get to know if there was an actual problem.

I'm open for ideas and discussions and in my opinion the exit code exclude filter would be the best solutuion.

**Comment by Paul-Weisser** [comment]
I agree with you. Personally, I would only need to exclude the 41301 but I can think of szenarios where excluding other return codes would be useful.

I have prepared this feature in #284
