### ISSUE TITLE
Invoke-icingacheckhttpstatus - unknown

### ISSUE THREAD

**Issue by haytxy** [Icinga/icinga-powershell-plugins#286]
hello, 

testing with curl gives me http 200.
![image](https://user-images.githubusercontent.com/79607995/155030229-77673034-57a6-4d2d-814d-c911b24daf65.png)

using Invoke-icingacheckhttpstatus gives me an unknown for response time.
![image](https://user-images.githubusercontent.com/79607995/155030541-cdb7be40-0736-4197-af0a-bf38605442ed.png)

any idea how to approach this issue.

mj

**Comment by haytxy** [comment]
tested locally
![image](https://user-images.githubusercontent.com/79607995/155031564-c9bf43a9-f8fb-4a4d-a8ec-e03cc7fbe7e0.png)

**Comment by LordHepipud** [comment]
Thank you for the issue. I will have a look on this.
Does this happen only to this address or is it a general problem with the plugin and all websites?

**Comment by stevie-sy** [comment]
@LordHepipud  the author also created a thread in the community https://community.icinga.com/t/invoke-icingacheckhttpstatus-unknown/9281/2 

For me it looks like the "problem" is the subroutine  `Get-IcingaCheckHTTPQuery`. You alway run  `Start-IcingaTimer`, but you call  `Get-IcingaTimer` only if there is a content. 

In my eyes you should run 
`$HTTPData.Add('RequestTime', (Get-IcingaTimer -Name 'HTTPRequest').Elapsed.TotalSeconds);`
always. 

Why there is no return content, only the author can answer. ... just my 5 cents :-)

**Comment by LordHepipud** [comment]
Thanks, yes - that was the problem
