### ISSUE TITLE
Invoke-IcingaCheckCPU - Performance Issue with 40 CPUs

### ISSUE THREAD

**Issue by Philipp4292** [Icinga/icinga-powershell-plugins#302]
Hello,

we are currently migrating our old nsclient to the new icingaagent.
I encountered the problem, that the Invoke-IcingaCheckCPU Performance varies and I can't quite tell why.

When I test the command on a 40 CPU Hardware the first run takes 43 - 70 seconds. The second run takes less than a second (see "Command Measure.png")

![Command Measure](https://user-images.githubusercontent.com/25362925/168826652-143a73f6-edda-4dc2-b817-9ea47368c8ac.png)

So I configured the check in the director with the following main properties (see "apply.png" and "template.png").
![template](https://user-images.githubusercontent.com/25362925/168827650-bf84e897-525d-4842-927f-287bb988a365.png)
![template2](https://user-images.githubusercontent.com/25362925/168828549-57f65531-8dcd-4da7-84ff-769edd245df1.png)
![apply](https://user-images.githubusercontent.com/25362925/168827680-e5842bcc-8ad1-43eb-8723-faeeddd7abfa.png)

The check exceeds the 60sec timeout quite often.

What's the difference between the check configured in the director and using the check the 2nd time in the Powershell itself?
Where is the bottleneck?

Thanks.

-Philipp

**Comment by LordHepipud** [comment]
Hello,

Thank you for the issue. The performance bottleneck comes from initializing Performance Counter objects and other elements which are always loaded over and over again, if the check is executed by Icinga.
The second call within the same PowerShell has all required components and libraries for Performance Counters loaded, therefore it is faster.

We highly recommend using the [API-Check forwarder feature](https://icinga.com/docs/icinga-for-windows/latest/doc/110-Installation/30-API-Check-Forwarder/), which will execute the check within an internal daemon over a REST-Call. This ensures that everything is already loaded within the daemon, reducing CPU and execution time bottlenecks.

**Comment by Philipp4292** [comment]
Hello, 
thank you for the hint, but it does not quite work.

So according to the doc I did this:

> Use-Icinga;

###Installing the two components restapi and apichecks
> Install-IcingaComponent -Name 'restapi';
> Install-IcingaFrameworkComponent -Name apichecks -Release;

###Registering a Backgrounddaemon and adding IcingaCheck*
> Register-IcingaBackgroundDaemon -Command 'Start-IcingaWindowsRESTApi';
> Add-IcingaRESTApiCommand -Command 'Invoke-IcingaCheck*' -Endpoint 'apichecks';

### Enabling the FrameworkApiChecks
> Enable-IcingaFrameworkApiChecks;

### Restarting the Service
> Restart-IcingaWindowsService;

Modules are in place 
![image](https://user-images.githubusercontent.com/25362925/168964651-943cf394-28fd-4acf-b29c-fd9f197580ea.png)

Services are running
![image](https://user-images.githubusercontent.com/25362925/168964727-76ca2e87-afdc-4aed-9786-950a2c7a75c7.png)

What am I missing?

Thank you.
-Philipp

**Comment by LordHepipud** [comment]
Hello,

please do not install additional components, because the REST-Api and Api-Check feature is included with the latest Icinga for Windows versions.

Please follow the installation instruction on the [REST-Api Documentation](https://icinga.com/docs/icinga-for-windows/latest/doc/110-Installation/30-API-Check-Forwarder/)

Basically, you only have to remove these components:

```powershell
Uninstall-IcingaComponent -Name 'restapi';
Uninstall-IcingaComponent -Name 'apichecks';
```

Afterwards simply restart the service

```powershell
Restart-IcingaWindowsService;
```

Please also make sure that you have the service binary installed

```powershell
Install-IcingaComponent -Name 'service';
```

**Comment by Philipp4292** [comment]
Hello,

we will buy 2 days of consulting. You can close the issue.
Thank you for your time.

- Philipp

**Comment by LordHepipud** [comment]
Hello

Thank you for your message. In case you require additional support here, please simply re-open the issue.

**Comment by Philipp4292** [comment]
For anyone who stumbles across this thread. 
The reason why the exec time was so high is that the ifw standard checks in Director do not use the REST API. https://github.com/NETWAYS/icinga-powershell-connector can be used as a workaround.
