### ISSUE TITLE
Invoke-IcingaCheckService MitigateUnknown not working

### ISSUE THREAD

**Issue by pakyg** [Icinga/icinga-powershell-plugins#309]
Hello,
I am trying to check the services, I passed him a series of specific services and on those not present the check reports me the status "unknown".
I saw that you need to pass the parameter "-MitigateUnknown 'Yes'" in order to skip the various unknowns and tell him to report "OK" but it doesn't work .. What am I wrong?

Best regards

Icinga 2.13.4
Plugins 1.9.0
Framework 1.9.2

![image](https://user-images.githubusercontent.com/70367256/180746669-1da32f80-7ea3-49da-bffe-42c861081efc.png)

**Comment by pakyg** [comment]
Hi, are there any updates on this issue?

Thanks

**Comment by LordHepipud** [comment]
Hello

Thanks for the issue. The `-MitigateUnknown` only ensures that empty check packages do not report unknown. If you specify a service which does not exist, it will be added to ensure that the user is aware that a certain services does not exist.

**Comment by pakyg** [comment]
Thank you very much ️
