### ISSUE TITLE
Invoke-IcingaCheckCertificate - add possibility to exclude thumbprints

### ISSUE THREAD

**Issue by Skeletitor** [Icinga/icinga-powershell-plugins#312]
Hi,

could you please provide the option to exclude thumbprints in 'Test-IcingaCertificateExcludePattern.psm1'?

Use case: Expired ca or subca certificates should not be removed from the CA Server, if they where used for signing. These kind of certificates will have the same issuer, subject and SAN and can't be excluded atm.

**Comment by LordHepipud** [comment]
Thank you for the feedback. Can you please test the linked PR?
I added the possibility that certificate Thumbprints can be excluded by the `-ExcludePattern` argument. Therefor we would not require a new argument for this.

**Comment by Skeletitor** [comment]
Works

Thank you very much!
