### ISSUE TITLE
Invoke-IcingaCheckTimeSync - time range for Warning/Critical doen't work

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icinga-powershell-plugins#314]
I started testing the latest Icinga-Powshell-Framework/Plugins on our test systems. It seems in the check Invoke-IcingaCheckTimeSync from the latest version has problems passing a range like -2s:2s.  
e.g.
the call 
Invoke-IcingaCheckTimeSync -Server x.x.x -Warning -2s:2s -Critical -4s:4s -Verbosity 2
brings this output:
![image](https://user-images.githubusercontent.com/38723488/185190798-ef3a0da7-bc50-4d85-8e3e-38e1032b6995.png)

the call with pos. values catches an error if the value is in minus.
Invoke-IcingaCheckTimeSync -Server x.x.x -Warning 2s -Critical 4s -Verbosity 2

in older versions it worked fine. 

The funny thing is: calling this in the ISE everything is fine! 
![image](https://user-images.githubusercontent.com/38723488/185192179-82ece3d0-2d71-49d3-aa20-92fe05d5b861.png)

So there must happen some mistake during running the check with
`'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' '-NoProfile' '-NoLogo' '-ExecutionPolicy' 'ByPass' '-C' 'try { Use-Icinga -Minimal; } catch { Write-Output '\''The Icinga PowerShell Framework is either not installed on the system or not configured properly. Please check https://icinga.com/docs/windows for further details'\''; Write-Output '\''Error:'\'' $($_.Exception.Message)Components:`r`n$( Get-Module -ListAvailable '\''icinga-powershell-*'\'' )`r`n'\''Module-Path:'\''`r`n$($Env:PSModulePath); exit 3; }; Exit-IcingaExecutePlugin -Command ...`

**Comment by LordHepipud** [comment]
Could you please test this Framework PR? https://github.com/Icinga/icinga-powershell-framework/pull/550

This should fix the issue

**Comment by LordHepipud** [comment]
Fixed with new Framework version

**Comment by stevie-sy** [comment]
Thanks for the fix. Works as expected  👍
