### ISSUE TITLE
Excluding Network Interfaces with friendly name

### ISSUE THREAD

**Issue by BT-Danny** [Icinga/icinga-powershell-plugins#316]
Hello there,
we want to exclude a Mellanox Interface for all our customers servers, but the problem is, the interfacenumber isn't fix and is sometimes different, so I can't just exclude interface 1 or 2. I would need to exclude ".*[Mm]ellanox.*" or something like that. I didn't found a proper way to exclude interfacenames, just team names, but NIC-Teaming isn't possible. Is there a workaround for it, so I can tell powershell-network Service to exclude all mellanox related interfaces?

best of regards:
Daniel

**Comment by LordHepipud** [comment]
Hello, tank you for the feature. It is possible, can you please check the linked PR?
There are other tasks as well to do, so please excuse if I don't respond to issues immediately ;)

**Comment by BT-Danny** [comment]
That's perfectly fine, thanks. I guess our customer needs to update the Icinga Agent to activate the new feature, as well as we need to update the command to get the new Cutoms Field for excluding the interface name, right?

**Comment by BT-Danny** [comment]
Nice, thank you. I just recognized the framework is installed via Ansible there and fixed to version 1.8.0, which explains why the Powershell Disc Problem still exists with these Machines. I try to figure out the upcoming dependencies and if the update will bring any problems for the clients. Thanks for implementing this new feature :)
