### ISSUE TITLE
Invoke-IcingaCheckTimeSync - undocumented "w32time"-service-monitoring

### ISSUE THREAD

**Issue by tectumopticum** [Icinga/icinga-powershell-plugins#322]
Currently this plugin contains an undocumented additional service-monitor of the "w32time"-service ("Time service"). If the service is installed but not running, a critical event is created.
In some virtual-environments it is not recommended to have this service running continuously.
I would recommend to remove this part from this plugin because it is not really working like lots of other plugins where you expect only one explicit check inside the plugin and no other hidden ones. Admins can use the Invoke-IcingaCheckService-plugin as additional check if they want to monitor the status of the time-service explicitly which is a more transparent and flexible solution instead of adding a argument to this plugin to configure the expected service-status.

**Comment by Philipp4292** [comment]
Can confirm.
Either set a switch for optional w32tm service monitoring or remove completely.

best regards,
Philipp
