### ISSUE TITLE
Invoke-IcingaCheckService: Invalid Perfdata for unknown services

### ISSUE THREAD

**Issue by cmaile** [Icinga/icinga-powershell-plugins#323]
In case of an not running service (service not in autostart after reboot) we got invalid perfdata for InfluxDBWriter:

`[2022-09-28 10:58:07 +0200] warning/InfluxdbWriter: Ignoring invalid perfdata for checkable '100!200' and command 'Invoke-IcingaCheckService' with value: paused_services=;;
Context:
	(0) Processing check result for '100!200'`

Example v1.9.0:

> `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -C Use-Icinga; exit Invoke-IcingaCheckService -Service test
> [UNKNOWN] Services: 1 Unknown [UNKNOWN] test: Service not found (0)
> \_ [UNKNOWN] test: Service not found: 0
> | 'pending_paused_services'=;; 'running_services'=;; 'pending_continued_services'=;; 'stopped_services'=;; 'pending_started_services'=;; 'service_count'=;; 'pending_stopped_services'=;; 'paused_services'=;; 'test_service_not_found'=;;`

Example v1.10.0:

> `H:\>C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -C Use-Icinga; exit Invoke-IcingaCheckService -Service test
> [UNKNOWN] Services: 1 Unknown [UNKNOWN] test: Service not found (0)
> \_ [UNKNOWN] test: Service not found: 0
> | 'summary::ifw_service::pendingstopped'=;; 'summary::ifw_service::pendingpaused'=;; 'default::ifw_service::testservicenotfound'=;; 'summary::ifw_service::running'=;; 'summary::ifw_service::pendingstarted'=;; 'summary::ifw_service::paused'=;; 'summary::ifw_service::pendingcontinued'=;; 'summary::ifw_service::count'=;; 'summary::ifw_service::stopped'=;;`
> 

It is also noticeable that the names of the performance data change between the versions v1.9.0 -> v1.10.0.

`pending_stopped_services vs summary::ifw_service::pendingstopped`

**Comment by LordHepipud** [comment]
Thank you for the issue. I will have a look on the missing performance data. For the label change, this is intended with v1.10.0:

https://icinga.com/docs/icinga-for-windows/latest/doc/100-General/01-Upgrading/
