### ISSUE TITLE
Invoke-IcingaCheckUNCPath - Add parameter to check as an individual user and wrong check state if share cant be acessed

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-plugins#332]
Hello,

I need to monitor some network shares. Those shares are only accessable for a specific subset of users. 
It whould be helpful if the check could execute with individual user credentials.

Right now - even if the check cant read the target share - the check state is OK with zeroed plugin output. Whoudn't UNKNOWN be more appropriate in this case?

```
[OK] \\target\share\without\access
\_ [OK] Free Space: 0B
\_ [OK] Size: 0B
\_ [OK] Total Free: 0B
```

I tested this with the latest releases.

**Comment by LordHepipud** [comment]
I have made a implementation draft of the UNC plugin, allowing different credentials.
Could you please test the linked PR?

Please ensure to delete the following file before testing the plugin:

```
\icinga-powershell-framework\cache\dll\IcingaUNCPath.dll
```

This file will be rebuild, once it was deleted before. The new DLL will then try to handle the authentication,

Example:

```powershell
icinga { Invoke-IcingaCheckUNCPath -Path '\\myshare' -User 'cstein@icinga' -Password (ConvertTo-IcingaSecureString -String 'my_secret_password' ) -Verbosity 3 } -DeveloperMode -RebuildCache
```

**Comment by K0nne** [comment]
The PR works as intended. Thank you so much :)
