### ISSUE TITLE
Invoke-IcingaCheckPerfcounter - parameter 'IgnoreEmptyChecks' doesn't work

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-plugins#348]
Hello!

We are using the parameter "IgnoreEmptyChecks" to prevent unwanted state changes in case, some perfcounters are not accessible.
This doesn't seem to work:

**config:**  
![image](https://github.com/Icinga/icinga-powershell-plugins/assets/34264690/476bc8eb-84ba-494b-82f2-a64cfaf46d02)

**state changes**:  
![image](https://github.com/Icinga/icinga-powershell-plugins/assets/34264690/7ac2ea9d-bca4-4a1c-9471-d3286df36b67)

**detail:**  
![image](https://github.com/Icinga/icinga-powershell-plugins/assets/34264690/5ce12dd8-b932-43ca-8b0f-e1bab272b0f2)

We are using framework and plugins in version 1.10.1.

**Comment by LordHepipud** [comment]
Can you please test the linked PR for the performance counter plugin?

This should summarize the result:

```powershell
Invoke-IcingaCheckPerfCounter -PerfCounter '\processor(*)\% processor time';

[UNKNOWN] Performance Counter [UNKNOWN] \processor(*)\% processor time
\_ [UNKNOWN] \processor(*)\% processor time
   \_ [UNKNOWN] Internal Counter Error: Failed to fetch all instances and objects for this performance counter. First error message: Example error message
```

**Comment by K0nne** [comment]
I tested the PR and on the console it works perfect.  
To change the behaviour in icingaweb2 I had to restart the icingapowershell-service.

**Comment by LordHepipud** [comment]
This is weird and shouldn't happen. Can you please try again? I just updated the PR with a minor adjustment.

You can use

```powershell
Copy-IcingaFrameworkCacheTemplate
```

To force the rebuild of the cache and `Restart-IcingaWindowsService` to cleanup.

**Comment by K0nne** [comment]
These are the results:

```
PS C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework> Copy-IcingaFrameworkCacheTemplate
PS C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework> Restart-IcingaWindowsService
[Notice]: Stopping service "icingapowershell"
[Notice]: Restarting service "icingapowershell"
PS C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework> icinga {Invoke-IcingaCheckPerfCounter -PerfCounter '\Hyper-V Dynamic Memory VM(*)\Average Pressure'}
[UNKNOWN] Performance Counter [UNKNOWN] \Hyper-V Dynamic Memory VM(*)\Average Pressure
\_ [UNKNOWN] \Hyper-V Dynamic Memory VM(*)\Average Pressure
   \_ [UNKNOWN] Internal Counter Error: Failed to fetch all instances and objects for this performance counter. First error message:
3
```
