### ISSUE TITLE
Invoke-IcingaCheckEventlog not working for Application and Services Logs section

### ISSUE THREAD

**Issue by drapiti** [Icinga/icinga-powershell-plugins#354]
The eventlog check does not seem to be working for logs outside of windows logs.
The following example does not find any events:

Invoke-IcingaCheckEventlog -Warning 0 -Critical 0 -LogName 'Microsoft-Windows-FailoverClustering/Operational' -IncludeEventId 1641 -IncludeEntryType Information -IncludeSource 'Microsoft-Windows-FailoverClustering'  -Verbosity 3
![image](https://github.com/Icinga/icinga-powershell-plugins/assets/4235359/506b8b67-15c6-401c-b343-254914dd8a7b)

**Comment by K0nne** [comment]
I think it's something with the slash in the middle. Have you tried to mask it?

**Comment by LordHepipud** [comment]
I'm not sure on how MSSQL logs work, but I do know the plugin is working properly in the Hyper-V space, having a similar log and source naming.

I will report back once I had a chance to test this on my test environment.

**Comment by drapiti** [comment]
Also there is another bug we are experiencing. Exclusively on Windows Server 2012 we get the following error:

[UNKNOWN] Icinga Exception: Could not compare "06/10/2023 22:08:23" to "2023/06/10 23.05.55". Error: "Cannot convert value "2023/06/10 23.05.55" to type "System.DateTime". Error: "String was not recognized as a valid DateTime.""
CheckCommand: Invoke-IcingaCheckEventlog Arguments: System.Collections.Hashtable StackTrace: at Get-IcingaEventLog, C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\compiled\icinga-powershell-plugins.ifw_compilation.psm1: line 8056 at Invoke-IcingaCheckEventlog, C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\compiled\icinga-powershell-plugins.ifw_compilation.psm1: line 1237 at Exit-IcingaExecutePlugin, C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-framework\cache\framework_cache.psm1: line 26525 at , : line 1
using the following settings as an example:
![image](https://github.com/Icinga/icinga-powershell-plugins/assets/4235359/bf57d5f8-947b-42eb-960b-0f63dd465c47)
Newer windows versions work perfectly fine with the exact same checks.

**Comment by tectumopticum** [comment]
which framework/plugin-version is used?

**Comment by drapiti** [comment]
This issue is no longer present with the updated versions.
