### ISSUE TITLE
Errors in Plugins_Bundle.conf

### ISSUE THREAD

**Issue by xxsamxx1991** [Icinga/icinga-powershell-plugins#358]
Failure in https://github.com/Icinga/icinga-powershell-plugins/blob/master/config/icinga/Plugins_Bundle.conf cause errors with `icinga2 daemon -C`.

1 Example for the 29 errors is this:

The line contains:
vars.ifw_api_command = invoke-icingacheckhttpstatus

The line should contain this:
vars.ifw_api_command = "invoke-icingacheckhttpstatus"

**Comment by LordHepipud** [comment]
Thanks! I fixed the config writer and updated all repositories with the correct config.
