### ISSUE TITLE
Invoke-IcingaCheckMemory Pagefile Percent Warning and Critical Threshold not working

### ISSUE THREAD

**Issue by audiocoach** [Icinga/icinga-powershell-plugins#367]
If you enter a percent value for PageFileWarning and PageFileCritical in the Invoke-IcingaCheckMemory Command you get a wrong output.

![image](https://github.com/Icinga/icinga-powershell-plugins/assets/64500854/ec0e53bd-42fe-4c24-b405-b48f0fd81e45)

![image](https://github.com/Icinga/icinga-powershell-plugins/assets/64500854/f8cde6c9-648f-4d62-9480-a5516769db4a)

Icinga 2.14.0
Icinga Web 2.11.4
Icinga Director 1.10.2
Icinga for Windows 1.11.0

**Comment by LordHepipud** [comment]
Thank you for the issue. This will be fixed with 1.11.1: #363

**Comment by audiocoach** [comment]
Problem still persits with 1.11.1

![image](https://github.com/Icinga/icinga-powershell-plugins/assets/64500854/27e6a927-321f-4a40-b516-10033c8195ec)

![image](https://github.com/Icinga/icinga-powershell-plugins/assets/64500854/3af724d7-1c1c-430f-884a-dba95adc44f5)

Icinga 2.14.1
Icinga Web 2.12.1
Icinga Director 1.11
Icinga for Windows 1.11.1
