### ISSUE TITLE
Invoke-IcingaCheckUsedPartitionSpace: Threshold problem in default mode (free space)

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-plugins#369]
Hello,

we have a problem with `Invoke-IcingaCheckUsedPartitionSpace` when we try to check the remaining disk space (mode "free space").
Even without the argument `-CheckUsedSpace` the check currently behaves like mode "used space".

(warning: <=10%, critical: <=5%)
![image](https://github.com/Icinga/icinga-powershell-plugins/assets/34264690/ed33fc0e-cc4d-44f9-867a-26925a092599)

Mode "used space" works fine.

Used versions:
![image](https://github.com/Icinga/icinga-powershell-plugins/assets/34264690/604b9a67-7c01-4e64-959c-ddaf90d19467)

**Comment by LordHepipud** [comment]
Hello,

this is not a bug but intended behavior. You have to change the thresholds based on the Icinga threshold handling, to change on the the values are interpreted: https://icinga.com/docs/icinga-for-windows/latest/plugins/doc/10-Icinga-Plugins/#icinga-plugins

**Comment by K0nne** [comment]
Thank you for the hint 🙂
