### ISSUE TITLE
IcingaCheckMemory results in Invalid Input Error

### ISSUE THREAD

**Issue by micha5strings** [Icinga/icinga-powershell-plugins#372]
All other checks (disk, load, service,...) seem to run just fine.
Checks are performed via ifw-api.

I already tried to run the memory check with JRE enabled, with the same result.
Running the check locally also results in the same error. (Invoke-IcingaCheckMemory)

On another machine (no vHost) the check runs fine with JRE disabled.
Enabling JRE results in the same error.

So I guess there is something funky happening with the permissions and some vHost issues on top.

Full Output:
Unable to parse input value. You have to add an unit to your input value. Example: \"10GB\". Allowed units are: \"B, KB, MB, GB, TB, PB, KiB, MiB, GiB, TiB, PiB\".\"

Full Command:
"'curl' '--verbose' '--tlsv1.2' '--fail-with-body' '--connect-to' '*******:5668:localhost:5668' '--ciphers' '*****' '--cert' '*****'--key' '*****' '--cacert' '*****' '--request' 'POST' '--url' '*****' '--user-agent' 'Icinga/v2.14.0' '--header' 'Accept: application/json' '--header' 'Content-Type: application/json' '--data-raw' '{\"Verbosity\":\"2\"}'"

Server-Versions:
Icinga2: 2.14.0-1
Icinga-Director: current master
Icinga Web: 2.11.4

Host-Versions:
Icinga PowerShell Framework: 1.11.0
Icinga Agent: 2.14.0
Plugins: 1.11.0
Service: 1.2.0

**Comment by LordHepipud** [comment]
Thank you for the issue. This will be fixed with 1.11.1: https://github.com/Icinga/icinga-powershell-plugins/pull/363
