### ISSUE TITLE
Invoke-IcingaCheckProcess - Exception calling "WarnOutOfRange" .. ConversionUnitMissing

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-plugins#373]
Hello,

I found a strange behaviour in Invoke-IcingaCheckProcess.

The following arguments are definded:

![image](https://github.com/Icinga/icinga-powershell-plugins/assets/34264690/8ac4cf6b-0544-42d5-b5de-222a75a73781)

..but the check shows sometimes this error and recovers from it, without any config change.
![image](https://github.com/Icinga/icinga-powershell-plugins/assets/34264690/58e4c4f2-af9a-4e29-b066-6fb209805ae4)

Framework: 1.11.0
Plugins: 1.11.0

**Comment by tectumopticum** [comment]
> Hello,
> 
> I found a strange behaviour in Invoke-IcingaCheckProcess.
> 
> The following arguments are definded:
> 
> ![image](https://user-images.githubusercontent.com/34264690/277654589-8ac4cf6b-0544-42d5-b5de-222a75a73781.png)
> 
> ..but the check shows sometimes this error and recovers from it, without any config change. ![image](https://user-images.githubusercontent.com/34264690/277654736-58e4c4f2-af9a-4e29-b066-6fb209805ae4.png)
> 
> Framework: 1.11.0 Plugins: 1.11.0

1. could you please show the "Executed Command" ("Inspect"-button)?
2. what is the output of the command if you execute it locally?

**Comment by K0nne** [comment]
1.
I dont know of a 'inspect' Button. We don't use the director.

2.
I also observed this behaviour on the commandline with the same error output.
Executing the same command twice worked without an error. 

At first I thought it was maybe a one time-mistake of the plugin, but seeking the flapping in icingaweb2, this has to be a bug.

**Comment by K0nne** [comment]
It even happens with conversion units:
![image](https://github.com/Icinga/icinga-powershell-plugins/assets/34264690/4295ff94-abeb-4065-8f7a-97d64fdb5349)

**Comment by christoph2497** [comment]
ref/NC/806910
