### ISSUE TITLE
IcingaPowerShell Framework - update does not work

### ISSUE THREAD

**Issue by MagnaFrisia90** [Icinga/icinga-powershell-plugins#374]
Hello,
I want to update from v1.11.0 => v1.11.1 to get the fix for "IcingaCheckMemory".
Therefore I have executed "update-icinga" and also tried to use the framework-Component Manager. But the update does not happen as shown on the screenshots:
 
![grafik](https://github.com/Icinga/icinga-powershell-plugins/assets/115451939/05340a6a-970b-425e-8e62-a63459ac6988)
![grafik](https://github.com/Icinga/icinga-powershell-plugins/assets/115451939/2311e1d0-c0c4-420c-9c7d-3be61105e6a3)
![grafik](https://github.com/Icinga/icinga-powershell-plugins/assets/115451939/b217fb90-3d44-409a-9428-8d30c76bc312)
Eventhough the action has been executed no update was performed. Version is still on v1.11.0 .
Any idea how to fix this ? How can I get the new version ?

Any help appreciated.
Thanks in advance.

Kind regards,
MagnaFrisia

**Comment by lazyfrosch** [comment]
As you are already on a version with a broken update routine, look at: https://github.com/Icinga/icinga-powershell-framework/pull/660#issuecomment-1699547922

But this is actually a framework issue, not related to plugins.

**Comment by MagnaFrisia90** [comment]
> As you are already on a version with a broken update routine, look at: [Icinga/icinga-powershell-framework#660 (comment)](https://github.com/Icinga/icinga-powershell-framework/pull/660#issuecomment-1699547922)
> 
> But this is actually a framework issue, not related to plugins.

Thank you for that information. 
How should I proceed ? Close with comment & mention #660 ?
