### ISSUE TITLE
Invoke-IcingaCheckUsedPartitionSpace: Output usage/free space in MB/GB

### ISSUE THREAD

**Issue by log1-c** [Icinga/icinga-powershell-plugins#5]
It would be nice to have the output of the check also tell the free/used values in MB/GB, not only the percentage :)

**Comment by LordHepipud** [comment]
Hello and thank you for the issue.
Do you want the output to be in the text or within the perf data output as well?

**Comment by log1-c** [comment]
Both would be great 😄 
Maybe similar to the output of the check_disk on Linux systems?
`
DISK OK - free space: / 8469 MB (79% inode=84%); /var 4774 MB (90% inode=98%); /tmp 1725 MB (99% inode=99%); /boot/efi 563 MB (98% inode=-);
`
![image](https://user-images.githubusercontent.com/24474580/71152724-80f05080-2237-11ea-9ec3-5834d91853f0.png)

**Comment by LordHepipud** [comment]
@Crited created a new branch for the plugin changes. Could you please test it and review the output? From our side this should be fine.

**Comment by log1-c** [comment]
I checked the new Module.
Is it by design, that not all perfdata values are filled?
![image](https://user-images.githubusercontent.com/24474580/74219174-5c9b7800-4cac-11ea-9311-65944ecfee2f.png)
This leads to problems with the graphite module when using custom templates instead of the default one, at least for me.
`Undefined index: icinga2.ST-WIN02-D-2103.services.Invoke-IcingaCheckUsedPartitionSpace.Invoke-IcingaCheckUsedPartitionSpace.perfdata.used_space_partition_c.value`

I don't quite get how the script creates the output, else I would've added it myself.
Would be very awesome to have the Bytes in the text output and the perfdata completely filled <3

**Comment by LordHepipud** [comment]
I'm wondering why the max value is not set because the plugin output is printing it with 100%.

For warning and critical - this part seems to be missing. Im going to add it.

**Comment by log1-c** [comment]
I'm playing around with the code atm.
I simply added `-Minimum 0 -Maximum 100` to line 83, and it shows it in the output on the powershell
```
[DBG]: PS C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\plugins>> 
[WARNING] Check package "Used Partition Space" - [WARNING] Partition C 
\_ [WARNING] Partition C: Value "13.75%" is greater than threshold "10%"
| 'used_space_partition_c'=13.68GB;;;0;99.46 'partition_c'=13.75%;10;20;0;100 
1
```
but not in Icingaweb2 :S

Will be interesting to see how you add the warn/crit for the used bytes, because I can't figure it out^^
At least
```
$DiskWarning = [math]::Round(($DiskSize.Value / 100) * $Warning)
	  $DiskCritical = [math]::Round(($DiskSize.Value / 100) * $Critical)
      $IcingaCheckByte = New-IcingaCheck -Name ([string]::Format( 'Used Space Partition {0}', $Letter )) -Value $ByteValueConverted.Value -Unit $PerfUnit -Minimum 0 -Maximum $DiskSize.Value -Warning $DiskWarning -Critical $DiskCritical ;
      
```
does not work...

**Comment by LordHepipud** [comment]
`Minimum` and `Maximum` for % units is not required in general, as it will auto-set the range from 0-100 by default.

I just made another commit, adding the warning / critical values calculated from % input.

For the maximum I have no idea why it is not displaying

**Comment by log1-c** [comment]
Thx a lot, looks good and the graphite template is working now as well
