### ISSUE TITLE
icinga-powershell-plugins not found on repository

### ISSUE THREAD

**Issue by weust1979** [Icinga/icinga-powershell-plugins#6]
After installing icinga-powershell-kickstart I try to run Install-Module icinga-powershell-plugins.
This results in:

> PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'icinga-powershell-plugins'. Try Get-PSRepository to see all available registered module repositories.
> At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
> + ...          $null = PackageManagement\Install-Package @PSBoundParameters
> +                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
>     + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

Not 100% sure I should be able to look it up on https://www.powershellgallery.com, but searching for "icinga" shows several results, but not this one.

**Comment by LordHepipud** [comment]
For the moment there is no PowerShell Gallery Package available. We will release the package their once the stable version is ready and no remaining issues are present.

Right now you can either use the RC Release Zip from this repository or the master. By using the Wizard / Framework, you will require to have either access to GitHub or download the Zip File and place it somewhere where you can access it.

Either a local / network path or a web url.

**Comment by weust1979** [comment]
OK. But then perhaps mention this (for now) in the 02-Installation.md?

**Comment by LordHepipud** [comment]
Oh crap - I prepared this part for the release of the PowerShell Gallery Repo.
Sadly this slipped through while comitting all changes 😱

Sorry for that!

**Comment by weust1979** [comment]
No problem. I did notice some other issues on other repo's as well, documentation wise.
Even a URL linking to a repo that doesn't exist anymore.

Is there a date (forgot the proper word here) for a release?

**Comment by LordHepipud** [comment]
The plan is to release both Framework and Plugins in January. The documentation will be polished a little more to cover more topics and a wider range of integrations

**Comment by weust1979** [comment]
Alright. Great. Looking forward to it.
I am mainly, at least for now, in the event log part.
There just doesn't seem to be a good way of reading event logs for use in Icinga 2.

I admin multiple Hyper-V clusters with FC storage. Being able to pull out the information I want would be very nice.

**Comment by LordHepipud** [comment]
PowerShell Gallery is now released: https://www.powershellgallery.com/packages/icinga-powershell-plugins
