### ISSUE TITLE
Icinga Plugins: Output Get-IcingaWindowsInformation : The term 'Get-IcingaWindowsInformation' is not ??????

### ISSUE THREAD

**Issue by patrickgidiuli** [Icinga/icinga-powershell-plugins#62]
Hi, updating to the latest version of the Plugins, I was presented with this error output:

Get-IcingaWindowsInformation : The term 'Get-IcingaWindowsInformation' is not recognized as the name of a cmdlet, function, script file, or operable 

program. Check the spelling of the name, or if a path was included, verify 

that the path is correct and try again.

At C:\Program Files\WindowsPowerShell\Modules\icinga-powershell-plugins\provide

r\disks\Icinga_ProviderDisks.psm1:45 char:24

+     $LogicalDiskInfo = Get-IcingaWindowsInformation 

Win32_LogicalDiskToPartition ...

How can I fix it?
Thanks so much

**Comment by Yonas-net** [comment]
Hiii @patrickgidiuli , Thanks for the report. Please try what I have written [here](https://github.com/Icinga/icinga-powershell-plugins/pull/34), if it does not work please contact us again.

Best,
YH

**Comment by Yonas-net** [comment]
By updating the framework should be the bug disappear.
