### ISSUE TITLE
Add support for cluster / mount point disk filters

### ISSUE THREAD

**Issue by drapiti** [Icinga/icinga-powershell-plugins#64]
In large enterprise environments it is common practice to use mount points on windows systems. With regard to the checkpartitionspace and the newer check disk health plugins it would be helpful to add filters for disk types as these tend to have different thresholds. Maybe some form of regex for mount point labels.
Types:
Local disks
Clustered disks
CSV
Mount points on local disks
Mount points on clustered disks

**Comment by Yonas-net** [comment]
Hiii @drapiti , Thanks for the report. At the moment you cannot filter by disk type, but with the parameters ``IncludeDisk`` and ``ExcludeDisk`` you also have the possibility to filter disks by their IDs.

Best,
YH

**Comment by LordHepipud** [comment]
Just out of curiosity: Is this something that will be resolved with the current cluster disk checks we are implementing?
Otherwise adding a filtering would be possible, I would how ever like to separate network mount points from local disk checks.

The reason is, that in case the network connection failes Windows will run into a timeout for every single network share not reachable.

Clustered disks will - as far as I can tell - be supported by a native cluster plugin we are currently working on.

@Yonas-net do I miss something here or would add the required support?

**Comment by drapiti** [comment]
> Just out of curiosity: Is this something that will be resolved with the current cluster disk checks we are implementing?
> Otherwise adding a filtering would be possible, I would how ever like to separate network mount points from local disk checks.
> 
> The reason is, that in case the network connection failes Windows will run into a timeout for every single network share not reachable.
> 
> Clustered disks will - as far as I can tell - be supported by a native cluster plugin we are currently working on.
> 
> @Yonas-net do I miss something here or would add the required support?

Yes so tipically by windows mount points we usually always refer to local disks in any case not network disks as is the case in linux. They can be both on a fixed local disk or a clustered disk, it would be convenient to filter this type of disk compared to a normal local disk.

**Comment by LordHepipud** [comment]
Just to follow up on this, I just added a new plugin to test for direct network shares. In addition we also added the cluster plugin collection for cluster shared volumes.

Is this still required for modification?

**Comment by drapiti** [comment]
> Just to follow up on this, I just added a new plugin to test for direct network shares. In addition we also added the cluster plugin collection for cluster shared volumes.
> 
> Is this still required for modification?

Maybe not necessary will resume testing the new plugins extensively asap with the latest fixes. We had been on hold. Thank you as always.

**Comment by LordHepipud** [comment]
Do you have an update for me on this issue? Is this resolved with the current plugins we provide?
