### ISSUE TITLE
PowerShell EventLog Monitoring Message in Output - Enhancement

### ISSUE THREAD

**Issue by radioactive9** [Icinga/icinga-powershell-plugins#66]
Hello

Please add Unique (Message) and Unique (Source) Fields in the Plugin Output. 
**Message**  : This is particularly important because there can be a possibility of two different EventID has same number. Also most of the time Users Work on the message from the ticketing tool rather than just the event ID which do not provide much of information. Understood that it might make the output clumsy when there are multiple event IDs monitored in the same service and all of them fire. Below change of including $eventEntry.Message makes it looks great and should be standardized

`$EventLogEntryPackage = New-IcingaCheckPackage -Name ([string]::Format('Between: [{0}] - [{1}] there occured {2} event(s). Message : {3}.', $eventEntry.OldestEntry, $eventEntry.NewestEntry, $eventEntry.Count, $eventEntry.Message)) -OperatorAnd -Verbose $Verbosity;`

**Source**  : Very useful field. For Example in MS-SQL event Log the Source field talks about the instance Name of the MS-SQL where the issue has happened. In a multi-instance DB the source field is vital as to know exactly whether the eventID is generated on instance A or in instance B. This one I think need more change of the code - at the first pull of event data itself. Always note - EventSource + EventID combination makes a log entry unique. EventID alone may not be unique by itself. EventSource is very crucial field. Please include this as an option as well as part of the Plugin Output

May be displaying the Message and Source can be a switch or option that can turn on or turn off based on the customer requirement

**Comment by radioactive9** [comment]
The eventLog Monitoring is very CPU intensive.
When multiple eventIDs are monitored in multiple single service on the same server the CPU struggles a lot. 
I have tested 47 EventID in 47 Single Service and it really thrashes the CPU badly. 
The reason behind creating 47 single service is because when 2 event ID fires together at the same sampling interval customer need 2 tickets instead of 1. 
Some documents related to improvement of performance in log monitoring
https://devblogs.microsoft.com/scripting/how-to-improve-the-performance-of-a-powershell-event-log-query/
https://www.reddit.com/r/PowerShell/comments/69kbkd/getwinevent_vs_geteventlog_performance/
https://stackoverflow.com/questions/60601715/event-log-query-with-get-winevent-get-eventlog-is-very-slow-when-querying-shut

This also suggest that having Provider as filter parameter is better than having Log Name mentioned as Filter

**Comment by bobapple** [comment]
> The eventLog Monitoring is very CPU intensive.
> When multiple eventIDs are monitored in multiple single service on the same server the CPU struggles a lot.
> I have tested 47 EventID in 47 Single Service and it really thrashes the CPU badly.
> The reason behind creating 47 single service is because when 2 event ID fires together at the same sampling interval customer need 2 tickets instead of 1.
> Some documents related to improvement of performance in log monitoring
> https://devblogs.microsoft.com/scripting/how-to-improve-the-performance-of-a-powershell-event-log-query/
> https://www.reddit.com/r/PowerShell/comments/69kbkd/getwinevent_vs_geteventlog_performance/
> https://stackoverflow.com/questions/60601715/event-log-query-with-get-winevent-get-eventlog-is-very-slow-when-querying-shut
> 
> This also suggest that having Provider as filter parameter is better than having Log Name mentioned as Filter

I created a separate issue for this

**Comment by LordHepipud** [comment]
I have created a PR to improve the plugin alot and to ensure the output is more accurated.

Changes made:
* Plugin will by default only go back 2 hours on first run or by using `-DisableTimeCache` (improves Performance a lot)
* Added log message to output on different check element on Verbosity 1
* Added filter for eventlog source
* Filtering for EventID's is now working properly by using the EventId instead of the InstanceId
* Changed grouping of events by Source instead of message (reduces output)

Waiting for tests and feedback for this now.
