### ISSUE TITLE
IcingaCheckService with wildcard includes service name with wildcard in check

### ISSUE THREAD

**Issue by jprusch** [Icinga/icinga-powershell-plugins#79]
How to reproduce:

- Execute InvokeIcingaCheckService -Service Win*

Expected result:

- Check on all services starting with "Win"

Actual result:

- Check on all services starting with "Win"
- But additionally a check on service "Win*" which is always UNKNOWN
- Resulting always in UNKNOWN check result

Remark:
- Excluding "Win*" with another parameter doesn't work

Example:
icinga> Invoke-IcingaCheckService -Verbosity 2 -Service Win* -Status Running
[UNKNOWN] Check package "Services" (Match All) - [UNKNOWN] Win*: Service not found
\_ [OK] Service "Windows Defender Antivirus Service (WinDefend)": Running
\_ [OK] Service "Windows-Remoteverwaltung (WS-Verwaltung) (WinRM)": Running
\_ [OK] Service "Windows-Verwaltungsinstrumentation (Winmgmt)": Running
\_ [OK] Service "WinHTTP-Web Proxy Auto-Discovery-Dienst (WinHttpAutoProxySvc)": Running
\_ [UNKNOWN] Win*: Service not found
3

**Comment by LordHepipud** [comment]
Thank you for the report. This is an interesting issue.
Will be resolved quickly - thanks a lot!

**Comment by LordHepipud** [comment]
I have provided a fix on the linked PR for this - could you please test if it resolved the issue on your side?
Once done I will merge the PR.

Thank you again!

**Comment by jprusch** [comment]
GREAT! Works now:

icinga> Invoke-IcingaCheckService -Verbosity 2 -Service win*
[OK] Check package "Services" (Match All)
\_ [OK] Service "Windows Defender Antivirus Service (WinDefend)": Running
\_ [OK] Service "Windows-Remoteverwaltung (WS-Verwaltung) (WinRM)": Running
\_ [OK] Service "Windows-Verwaltungsinstrumentation (Winmgmt)": Running
\_ [OK] Service "WinHTTP-Web Proxy Auto-Discovery-Dienst (WinHttpAutoProxySvc)": Running
| 'pending_paused_services'=0;; 'running_services'=4;; 'pending_continued_services'=0;; 'stopped_services'=0;; 'pending_started_services'=0;; 'service_count'=4;; 'pending_stopped_services'=0;; 'paused_services'=0;; 'service_winhttpweb_proxy_autodiscoverydienst_winhttpautoproxysvc'=4;;4 'service_windowsremoteverwaltung_wsverwaltung_winrm'=4;;4 'service_windowsverwaltungsinstrumentation_winmgmt'=4;;4 'service_windows_defender_antivirus_service_windefend'=4;;4
0
