### ISSUE TITLE
IcingaCheckUsedPartitionSpace - used/total space in output line

### ISSUE THREAD

**Issue by picardncc1701** [Icinga/icinga-powershell-plugins#83]
I want to see immediatly how much space is left and how much space has this partition totallly. Especially in the headline of a notification. I think at this moment, this isn't possible with this plugin.

On NSClient that is easy to realize like this:

> Plugin-Ausgabe
OK C:: 68.628GB/79.509GB used

**Comment by LordHepipud** [comment]
Hello and thank you for the issue. You are correct, right now the plugin does only output the used partition space in % on notifications.

```
[CRITICAL] Check package "Used Partition Space" - [CRITICAL] Partition C, Used Space Partition C
\_ [CRITICAL] Partition C: Value "39.62707%" is greater than threshold "30%"
```

In the performance metrics both values are printed - % and in Bytes.

I just want to ensure we do not crowd the plugin output too much.
