### ISSUE TITLE
Invoke-IcingaCheckPerfcounter throws exception on MSSQL categories

### ISSUE THREAD

**Issue by loganbibby** [Icinga/icinga-powershell-plugins#92]
When using `Invoke-IcingaCheckPerfcounter` to check an MSSQL category counter, an exception is thrown and it seems to be related to how Icinga is encapsulating (or, more likely, not encapsulating) the counter name. I restored the Director Basket generated by the framework. 

The counter I'm using is: `\MSSQL$$ABC:Databases(XYZ)\Data File(s) Size (KB)`. (Replacing ABC and XYZ with it's correct information, of course.)

Exception generated:
`Check package "Performance Counter" (Match All) - [UNKNOWN] \MSSQL$ABC:Databases(XYZ)\Data File(s) Size (KB): Exception calling "NextValue" with "0" argument(s): "Instance 'XYZ' does not exist in the specified Category."`

If I run the command directly in Powershell, I get a proper result:
```
PS C:\Users\Administrator> Install-Module 'icinga-powershell-plugins';
PS C:\Users\Administrator> Invoke-IcingaCheckPerfCounter -PerfCounter '\MSSQL$ABC:Databases(XYZ)\Data File(s) Size (KB)' -Warning 1 -Critical 2
[CRITICAL] Check package "Performance Counter" - [CRITICAL] \MSSQL$ABC:Databases(XYZ)\Data File(s) Size (KB)
\_ [CRITICAL] Check package "\MSSQL$ABC:Databases(XYZ)\Data File(s) Size (KB)"
   \_ [CRITICAL] \MSSQL$ABC:Databases(XYZ)\Data File(s) Size (KB): Value "492928" is greater than threshold "2"
| 'mssqlABCdatabasesXYZdata_files_size_kb'=492928;1;2
2
```

I've tried to encapsulate the category in `"` and `'` at the service and command levels, removed the array and made the field a string (in case it was something weird happening with the join), and tried various ways of escaping the value to no avail. 

Versions:
- Icinga 2.8.2 on Linux
- Windows Server 2019 Datacenter
- Latest version of icinga-powershell-plugins

**Comment by LordHepipud** [comment]
Thank you for the report. I never run into this issue so far, but basically with the Icinga Director it should be enough to add the entire counter into single quotes and propably escape the `$` in the string with another `$` (as you seem to have done).

Could you please enable the debug log on the Icinga Agent (`Enable-IcingaAgentFeature debuglog`) and restart the services afterwards with `Restart-Service icinga2`.

Once the check get's executed, we can have a look inside the log to see on how the check is executed by Icinga 2.

You can tail the debug log by using `Read-IcingaAgentDebugLog`.

Thank you in advance!

**Comment by LordHepipud** [comment]
I did some testing on this and my initial assumption seems to have been correct. Here is a working example:

![image](https://user-images.githubusercontent.com/5050288/99510402-55b23c00-2987-11eb-8ebd-01cdd8b46c9f.png)


You have to escape the `$` inside the Performance Counter name with another `$`, as you already it.
In addition you will have to place a `'` (single quote) around the entries for each array element. Once done, the check works as expected:

![image](https://user-images.githubusercontent.com/5050288/99510621-9742e700-2987-11eb-9bf8-8c7a6a71640e.png)

I will add some knowledge base entry for this to ensure this is documented somewhere

**Comment by LordHepipud** [comment]
I made this also clear within the newly introduced [knowledge base](https://icinga.com/docs/windows/latest/doc/10-Knowledge-Base/) for Icinga for Windows.

Is this issue resolved with that?

**Comment by LordHepipud** [comment]
I will close this issue now because as far as I can tell the issue should be resolved. If not, please feel free to re-open it.
