### ISSUE TITLE
Add filtering by "total core" in Invoke-IcingaCheckCPU

### ISSUE THREAD

**Issue by ErwinE** [Icinga/icinga-powershell-plugins#93]
Hello,

we have more than 700 Windows devices in our environment which should be monitored standardized.
With the new IcingaCheckCPU check we have many alerts where only some single cores on systems have a high usage.
But we want to get only alerts, if the "total usage" is over the thresholds.
There would be 2 solutions which should work:
1. Add extra thresholds only for total_core
2. Add support to filter by total core. There is already a function to filter by single cores, but not the total core.

I think implementing both solutions would improve the check for large environments.

Best Regards and Thanks,
Erwin

**Comment by LordHepipud** [comment]
Hello and thank you for the issue. You can already filter for the total avg. Simply set the `-Core` argument to `_Total`.
This will filter out all other cores.

As this is not very clear within the docs, I will add it to the description of the argument. Does this help you?

**Comment by ErwinE** [comment]
Hello LordHepipud,

thank you for your help. Yes, this is actually helpful. I tried "total" and "core_total" but not "_total". I wasn´t aware of this.

Adding this to the documentation is a great idea ;)

Best,
Erwin
