### ISSUE TITLE
Invoke-IcingaCheckService returns critical count in perfdata

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icinga-powershell-plugins#96]
Invoke-IcingaCheckService returns als a critical count in perfdata which shouldnt be there if we cant set a critical threshhold (which is useless on state checks)

Please remove the critical count in perfdata.
```
PS C:\Users\Administrator> Invoke-IcingaCheckService -Service 'VMTools'
[OK] Check package "Services"
| 'service_vmware_tools_vmtools'=4;;4 'pending_paused_services'=0;; 'running_services'=1;; 'pending_continued_services'=0;; 'stopped_services'=0;; 'pending_started_services'=0;; 'service_count'=1;; 'pending_stopped_services'=0;; 'paused_services'=0;;
```

![grafik](https://user-images.githubusercontent.com/6574967/99262805-afe3bd80-281e-11eb-871d-4c2617e0abc5.png)

**Comment by LordHepipud** [comment]
Hello and thank you for the issue. The critical count is actually valid, as we compare the current value (4 = Running) with the value specified by `-Status`. By default we will use the value 4 to compare against, in case `-Status` is not set.

Therefor this behaviour is actually correct.

**Comment by Mikesch-mp** [comment]
Ahh ok, maybe my example is not correct. On the shell i forgot the -State, but in the icinga command its present and the critical treshhold is still in the perfdata.

**Comment by LordHepipud** [comment]
Hello, how shall we proceed on this case? Is the issue resolved or is anything still unclear/open?

From my side the critical value is fine, as this is the plugin default.

**Comment by Mikesch-mp** [comment]
Maybe have a litle talk one day, but close it for now

**Comment by LordHepipud** [comment]
Allright, we will do this ! Thanks a lot! :D
